#!/usr/bin/env bash
# deploy/generate-age-key.sh — 產 age 金鑰（B′＝passphrase 加殼 identity）
#
# ＝rev5:RUNBOOK §15.2 步驟 1 的**機器化版本**：守衛與自檢內建，消除「手冊裡的可執行片段與實作
#   各寫一份而漂移」那類失效（rev4:L-199）。手冊仍保留同口徑的 inline 形作為本腳本不可用時的退路。
#
# 用法（不強制 CWD——Dockerfile 以本腳本所在目錄定位）：
#   bash deploy/generate-age-key.sh                            # 第一把：產到預設 ~/.config/sops/age/keys.txt
#   bash deploy/generate-age-key.sh keys-fork260509-rev6.txt   # 同機第二把：同目錄**非預設**長檔名
#     （★跨代並存機的正解——該機已有前代 identity 時走這條，見 rev5:RUNBOOK §15.2 步驟 1 註記）
#
# 何時用：①新機／新成員加入（rev5:RUNBOOK §15.2 步驟 1）②換機重建 ③撤銷演練需第二把（rev5:RUNBOOK §15.3 準則 5）
#   ④金鑰或 passphrase 遺失後重新加入（rev5:RUNBOOK §15.5）。
#
# ★passphrase 只在你腦中：本腳本**不接受、不記錄、不回顯**——由 age 自己向容器 tty 索取。
#   遺失＝該 identity 永久失效、其加密的密文不可解（離線備份義務**含 passphrase 本身**、rev5:RUNBOOK §15.5）。
# ★需真終端（`age -p` 要 tty）；非互動情境**吵鬧失敗且零副作用**。
# ★同機第二把務必用非預設檔名：金鑰一律落 ~/.config/sops/age。取 keys-fork260509-rev6.txt
#   這個名時 wrapper 會**自動選它**（單檔掛到容器內預設尋鑰路徑、容器內恰一把 identity），
#   解密毋須帶任何環境變數；用其他檔名（如 rev5:RUNBOOK §15.3 撤銷演練鑰）則以 RV6_AGE_KEY_FILE 給
#   **host 端絕對路徑**覆寫（rev5:RUNBOOK §15.2 步驟 1 註記）。
# ★檔名取 **repo 目錄名**（`keys-fork260509-rev6.txt`）而非短代號：跨代並存的機器上短代號家族
#   必撞名——此即 rev4:0084 付過代價換來的命名紀律（同源＝SECRETS_DIR 亦以 repo 目錄名為根）。
# ★age 走容器（deploy/Dockerfile.age）＝rev5:ADR 0011 ③ 類一次性輔助工具：沿 latest、版本不落字面，
#   每次產鑰 `docker build --pull --no-cache` 取真最新（防「假 latest」被 docker 層快取凍住）；
#   host 端零 age 依賴、容器零落地檔（產物由 host shell 收 stdout、rev4:P1.6 同慣例）。
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# ★映像 tag 取 **repo 目錄名**（非 compose project name `rev6-admin`、非刀號）：image tag 是
#   機器全域識別字，同機並存 fork260509-rev1~rev6 與其他專案時短代號必撞名——撞名後
#   `--no-cache` 重建會靜默覆蓋他人 tag、離線退回分支會靜默沿用他人映像（rev4:0084 命名紀律；
#   同源＝SECRETS_DIR／`~/.cache/fork260509-rev6/`／金鑰檔名 keys-fork260509-rev6.txt）。
AGE_IMAGE="fork260509-rev6/age:local"
BEGIN_MARK="-----BEGIN AGE ENCRYPTED FILE-----"
END_MARK="-----END AGE ENCRYPTED FILE-----"
KEYDIR="$HOME/.config/sops/age"
KEYNAME="${1:-keys.txt}"
KEYS="$KEYDIR/$KEYNAME"

# ---- 參數自檢：檔名不得帶路徑（防穿越、也防誤把金鑰產到容器讀不到的地方）----
case "$KEYNAME" in
  */*|"")
    echo "FAIL：參數是**檔名**、不是路徑（例：keys-fork260509-rev6.txt）——金鑰一律落 $KEYDIR" >&2
    exit 1 ;;
esac

# ---- 取工具映像（rev5:ADR 0011 ③ 類：每次 build --pull --no-cache＝真最新；離線退回既有映像＋警示）----
# ★build context 必須為**空**——故以 stdin 餵 Dockerfile（`-` ＝零位元組 context）而非給目錄：
#   .dockerignore 只在 **context root** 生效，deploy/ 下沒有那一份，repo 根那份（明文封殺
#   deploy/secrets/＝compose 明文回退落點、deploy/dev-certs/＝本機真私鑰）因此完全不適用；
#   若把 deploy/ 當 context，legacy builder（DOCKER_BUILDKIT=0／舊 engine）會把整棵目錄含上述
#   兩處打包上傳 daemon。本 Dockerfile 零 COPY-from-context，空 context 亦讓日後誤加
#   COPY 立即紅、不會悄悄把機密拉進來。
if ! docker build --pull --no-cache -t "$AGE_IMAGE" - < "$SCRIPT_DIR/Dockerfile.age"; then
  if docker image inspect "$AGE_IMAGE" >/dev/null 2>&1; then
    echo "警示：映像重建失敗（離線／限流？）——沿用本機既有 ${AGE_IMAGE}，其 age 未必是最新版。" >&2
  else
    echo "FAIL：映像重建失敗、本機亦無既有 $AGE_IMAGE ——首次產鑰需能連外重建一次：" >&2
    echo "        docker build --pull --no-cache -t $AGE_IMAGE - < deploy/Dockerfile.age" >&2
    exit 1
  fi
fi

# ---- 覆蓋前最後一道閘（★rev5:RUNBOOK §15.2：覆蓋＝永久銷毀既有私鑰、其密文即刻不可解）----
mkdir -p "$KEYDIR"
chmod 700 "$KEYDIR"
if [ -e "$KEYS" ]; then
  echo "FAIL：$KEYS 已存在——覆蓋＝永久銷毀該私鑰、版控內以它加密的密文即刻不可解；停手。" >&2
  echo "      跨代並存機（該機已有前代 identity）＝保留舊鑰、另產第二把，檔名取 repo 目錄名：" >&2
  echo "        bash deploy/generate-age-key.sh keys-fork260509-rev6.txt" >&2
  echo "      該檔名會被 wrapper 自動選用（單檔掛載），之後解密照常跑、毋須帶環境變數：" >&2
  echo "        python3 deploy/decrypt-secrets.py" >&2
  echo "      全文＝rev5:RUNBOOK §15.2 步驟 1 註記。" >&2
  exit 1
fi

# rev4:P1.2 同構：stdin 有 tty 才配 -i -t（age -p 需真 tty；非互動時吵鬧失敗且零副作用）
TTY_FLAGS=()
if [ -t 0 ]; then
  TTY_FLAGS=(-i -t)
fi

echo
echo "即將產生金鑰到 $KEYS ——age 會要求輸入 passphrase 兩次（設定＋確認）。"
echo "★該 passphrase 只存在你腦中；★絕不要貼進任何對話或訊息。"
echo "★★提示文字看不見（容器 pty 把提示與資料併成同一流、由本腳本捕捉；rev4:P1.2 同病）："
echo "  畫面停住即是在等你打字，打完 Enter、共兩次；輸入不回顯屬正常。"
echo "★絕不空答：空答會讓 age 自動生成一組你看不到的 passphrase（本腳本偵測到即擋下）。"
echo

# ---- 產鑰（容器內管線；產物只走 stdout、容器零落地檔）----
if ! RAW=$(docker run --rm "${TTY_FLAGS[@]}" "$AGE_IMAGE" sh -c 'age-keygen | age -p -a'); then
  echo "FAIL：產鑰未完成（passphrase 中斷／兩次不一致／取不到 tty）——既有檔一 byte 未動、未落任何檔。" >&2
  echo "      ★捕捉流一律不回印（pty 回顯萬一沒關會夾帶 passphrase）；要看 age 原文請手動重現：" >&2
  echo "        docker run --rm -it $AGE_IMAGE sh -c 'age-keygen | age -p -a'" >&2
  exit 1
fi

# ---- pty 併流正規化：剝 CR → 以 armored 區塊界線萃取私鑰、Public key 行另捕為公鑰，餘行丟棄 ----
RAW=${RAW//$'\r'/}
if printf '%s' "$RAW" | grep -q "autogenerated passphrase"; then
  echo "FAIL：偵測到空答——age 已自動生成一組 passphrase，而該串只印在你看不到的併流裡＝" >&2
  echo "      這把鑰匙沒有人能解開。未落任何檔；請重跑並在兩次提示都實際輸入。" >&2
  exit 1
fi
# ★取首個命中即 exit（不接 `| head -1`：pipefail 下 head 早退會讓上游吃 SIGPIPE、整段被 set -e 幹掉）
PUBKEY=$(printf '%s\n' "$RAW" | awk 'match($0, /Public key: age1[0-9a-z]+/) { print substr($0, RSTART + 12, RLENGTH - 12); exit }')
ARMOR=$(printf '%s\n' "$RAW" | awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
  !on { i = index($0, b); if (!i) next; on = 1; $0 = substr($0, i) }
  { j = index($0, e); if (j) { print substr($0, 1, j + length(e) - 1); exit } print }')
if [ -z "$ARMOR" ] || [ -z "$PUBKEY" ]; then
  echo "FAIL：捕捉流裡找不到 armored 私鑰區塊或 Public key 行——未落任何檔；請手動重現查 age 原文。" >&2
  exit 1
fi

# ---- 落檔（★先寫 .new 再 mv：任何中途失敗都不會讓半截內容成為 ${KEYS}）----
( umask 077; printf '%s\n' "$ARMOR" > "$KEYS.new" )
mv "$KEYS.new" "$KEYS"
chmod 600 "$KEYS"

# ---- 產物自檢（★布林形、只印 True/False 與 byte 數，絕不印內容 byte；rev4:L-193）----
# ★不另驗「明文私鑰形」：首行等於 armored 起始界線即蘊含它不是明文私鑰行，該檢查恆為 False
FIRST=$(head -1 "$KEYS"); LAST=$(tail -1 "$KEYS")
CR=$(tr -cd '\r' < "$KEYS" | wc -c | tr -d ' '); BYTES=$(wc -c < "$KEYS" | tr -d ' ')
[ "$FIRST" = "$BEGIN_MARK" ] && [ "$LAST" = "$END_MARK" ] && ARMORED=True || ARMORED=False
echo "自檢｜passphrase 加殼＝${ARMORED}｜CR 數＝${CR}（應 0）｜bytes=${BYTES}｜公鑰行已捕捉＝True"
if [ "$ARMORED" != True ] || [ "$CR" != 0 ]; then
  echo "FAIL：產物不是 armored passphrase 加殼形（應以 $BEGIN_MARK 起首、$END_MARK 收尾、零 CR）" >&2
  echo "      ——passphrase 那步或萃取沒生效；刪檔重做" >&2
  exit 1
fi
echo "權限｜檔 mode=$(stat -c '%a' "$KEYS" 2>/dev/null || stat -f '%A' "$KEYS")（應 600）｜目錄 mode=$(stat -c '%a' "$KEYDIR" 2>/dev/null || stat -f '%A' "$KEYDIR")（應 700）"

echo
echo "===== 完成。下面這一行是你的**公鑰**（非機密、可貼訊息交付管理者） ====="
echo "Public key: $PUBKEY"
echo "======================================================================"
echo
echo "接著（rev5:RUNBOOK §15.2 步驟 3~4）：管理者把該公鑰加進 .sops.yaml 的 age: 清單 →"
echo "  ./deploy/sops.sh updatekeys -y deploy/secrets.dev.enc.yaml → commit 密文 →"
echo "  你 git pull → bash tools/bootstrap.sh → python3 deploy/decrypt-secrets.py"
echo "★少了步驟 3，你的私鑰不在 recipient 清單裡＝拉到的密文一律解不開（rev5:RUNBOOK §15.2 末條）。"
