postgres_password: ENC[AES256_GCM,data:x4h31Ic6u2avk+13rUh6NfBhzK3aQKYAgsPJJWfADTGD/bo9cWfzYimTjRQPRXlK,iv:gzZZuJg6o8KZcLqAWx4gTUCmrHqFFQTLIUM2L1E25+g=,tag:gf/qAwgqGJzqvh+KRmGXHw==,type:str]
redis_password: ENC[AES256_GCM,data:Vh2kLEM+WnYCm43L6ZwuzsveO0638JffMrri5IddTzeNgkkjHM0KuN5yKEkXnMuS,iv:mHIZX9RyQjVy09guBm5ptvc+rfBokOD9kTJTGvsSXFg=,tag:BxBZhgs5p3REiQYQgqehXA==,type:str]
jwt_secret: ENC[AES256_GCM,data:v5/I96VI/qSkpBGhe99CJaEHqsJVn+xwUIKVL3n6B6nVR+3LMGgNOqndpemVbHnuE5pls1kYy7HglYnAe7x1ug==,iv:Ve/3UDyKxdCeHFizancSDOhNx0fosvo9XonBWISfs8w=,tag:VUjO6zpnb80eNmBLv0W62A==,type:str]
refresh_token_secret: ENC[AES256_GCM,data:iWJ8KtWVRzCLpDpaatcbn+v83ASOaDyNRUeHEkK23IXQ44+2LrEwFJysSmthQAIb0L3CVAn645d06s9RwcGbXg==,iv:B0QEwRs/U6ycP/kMxMIYaeAw6XhoyZPvQeQZrHOldlc=,tag:3J1Jamvyt9KRVEWqzHC8Tw==,type:str]
captcha_secret: ENC[AES256_GCM,data:hsJYrUDie0dRkHFX6Xyf6s+xMN/ajwBK0ybSI6pQ2yxx4HmlE0L0Xd7oi4jw1txW7lq7Cb7PYcNrkz4D042xTg==,iv:5alSCZoSMx48mBvwxZCxWhgnkk1MPtXG5z6ejN+2Xoo=,tag:l+oPcpKL94SiQwjDI/3q3Q==,type:str]
reaper_password: ENC[AES256_GCM,data:tkXn8Q0beiEWYwtRIm/EvLxvGJEIHw1GHNwYswCdByUIVV0fIEuqAus6NN+kk3/j,iv:FcYCSnT7UVWzjqk0Xiop7A/4caTPGJFXXDDwCoUnXfs=,tag:aQUxR1zSFrPlbugE5Zw/VQ==,type:str]
grafana_admin_password: ENC[AES256_GCM,data:peI2+scpAbxKeh7rUFnfcEQDzaddmLUHbEwC1dEEQ78=,iv:HVXL5wWH61m9cjT63r/9XE8BJ/u5Auakm8bQfdu/fxQ=,tag:dWhGdNrE2ztQNTgaLjmYmA==,type:str]
smtp_password: ENC[AES256_GCM,data:Nc1jhrao8k3OS4fPnGc6Irk9FHAHyuYnZFcp4I6r5vs=,iv:DscOCd+J1ZsmHldyxHAJP7WEMquqbGDuAfva5mtELmU=,tag:x55mMTxlPM6FPpdPM7K+bg==,type:str]
email_verify_secret: ENC[AES256_GCM,data:l7Kk+wWdaVLfZrwpYGt8DJBIWoLKKJ79HAU89PanGICgGxzVJLGDdBSrkCDPOdkMRyLjp7Dwwx0Y16wQCuXUog==,iv:brUxO+Cm+A58LNpvb49NJagN97GDKMeZhlJNyk/MWeI=,tag:SzypA6O6oS2AjBVvZw5veA==,type:str]
alert_webhook_url: ENC[AES256_GCM,data:NMM4rzmsvuOiMr63lXw5SqfVYWfAzJVkrmi8GJOoOOTC1HmZMDCmJNGWLn1Z1gH8lSMc,iv:BZso8ycDGeIMvI8EBcmh0r3gtFLQCqARaXuihGed88I=,tag:4dPddJ7lahdN8nD6pTpfpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCczlHMUhlZlVmYVNEVURn
            WStJVjN0d0RDYWxuZVp2V3libjdpWElKMmdjCjdXT2JsWlUxa3Y3OXMyRXU5TTRM
            RzVtVFNScldiQ2NCeXowU3BHdUNMYmMKLS0tIEw1ZUNBZ0VreHdVTTlXZ0ZSU01j
            MnljQ3JQQmlzaXFVd2xzUW5BTWVzTGMKgWtPJgaBXwJ2qZ2VCHCjKFL26zW7gmXt
            BNqy7+/Jlt/AqxH8WthgXDhdQabZCbuIZUSp07BOxC8si7x7CB+i1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e3y94d7p4wuk9rl7d4nkjmvcjmdw6drlemcvc363pyk9v735u3ks8kx4zn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bVM5V3lIZS9tMVhGUUds
            SlBqOWtPcFM5KzJDMkVTSUNZcThtRjZkeWo0CmVQcWk4cDRQL0dQN2MxM2xFbWps
            NFdMTFc0dXRCcHBLNXNrbXNoVDFHYTAKLS0tIE5Fd2ZqLytyc0FnUzRwUWVGSWdj
            V1poUHdXTG1IY215Y3FNVHNsTzN3UTQKhp72sxhY526Z1Upnf/qncxM/foVcNXgr
            Q41z/O5P4NNaodlLHry0B8MSRLP/+sL9g87nCNIPXDay3xR02ycyGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130ny8zzsvz89rkacw34c3nkpe9h9d36n7xvq8wecfym9jnf5js6sgj9dc5
    lastmodified: "2026-09-02T19:08:43Z"
    mac: ENC[AES256_GCM,data:CUtOCxjE5gPLHPSH+l7DU9vAKElmn0ba21rg8utGAkuR3FTIdi48vqGXYJOgnX50JsdO01FPbHwJprbko2IvfSK/UEXix0TsMvyEcTKAM0MEP/BOdyzq1oPOm+4Jk19PhRoNgaAnP5oun5aVosB1NJSi2ybmfol1vbOpVJ6POxY=,iv:AeHzEcwdePQWd60bqLOYhpBSq2atba/j23ZStj8OcrQ=,tag:M9tJATjrvw8Wib4BVoB+oA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
