#!/usr/bin/env python3
"""tools/fork-delta-lint.py — 機器式驗 base-web fork-delta「原行」紀律（憲法 §III 跨軌道 fork-delta 執行紀律）。

隨遷工具（承 rev5:tools/fork-delta-lint.py 逐字承襲、座標同名：源倉 `fork260509-soybean-admin-base/` @ `example`、
憲法 `.specify/memory/constitution.md`；RULES 名詞段「隨遷工具」）。rev6 拍板差異（002 刀；research R3-6／R10）：
  · token `rev5-inline`→`rev6-inline`（憲法 §III 標記字面）；新增型新檔檔頭形＝`<註解引導> [rev6-inline <軌道名>+ <刀名>] <理由>`
    （註解引導依檔型而異：`.ts` 與 `.vue` script 區 `//`、`.vue` template 區 `<!-- -->`；軌道名＝[`TRACK`] 之
    `[A-Z][A-Z0-9-]*`，**不限** §III.1 表首欄——名冊外之名不做名冊斷言、見 [`S1_NEW_FILE_FACE`] 射程界定；刀名＝該檔進場刀）。
  · 結構斷言改形：§III.2 ★段零列時 MUST 命中哨兵句「（空表——尚無 ★ 軌道；首列隨首刀 Amendment 落入。）」、否則 ≥1 列
    （rev5「≥4 列」樓地板守「名冊被無聲移除」、rev6 由哨兵句承擔同一目的；哨兵句與資料列並存＝矛盾亦 die）。
  · 加 `test` 子命令（只跑 self-test、離線、不掃 base-web、不碰源倉；供 pre-commit `for t in` 自測迴圈與 bootstrap
    `run_tool_test`）與 `--constitution <path>`（只供自身變異驗證、日常一律預設路徑）；用法錯 rc 64。
  · 修改型樓地板守：002 刀時 rev6 base-web 零 inline、rev5 之 `checked_total < 1 → die` 曾改為印明示不 die；003 刀起 base-web
    帶修改型 inline，復為 die（rc 2；spec-compliance-003 L4-4），掃描面可達性斷言（git diff 必 rc 0＋源倉必在 example）照留。
  · rev5 曾有三組語意守（rev5:B-061 假 toast／rev5:B-062 `$t` fallback／交付面必存字面），各隨其功能刀重定、002 刀 U0
    不遷（其標的檔在 002 刀當時的 rev6 base-web＝upstream example tip 零 inline、留著＝首跑必 die；憲法 §III.2 承襲指針明寫用途集隨
    rev6 刀序重定、不整表照搬）。

最原始源-基線＝`fork260509-soybean-admin-base/` @ `example` 分支 tip（實體目錄、須先切到；bootstrap 斷言在場）。
判定：base-web 若改動 example 既有 inline 行（該行不再逐字存在於我方版）→ 我方檔內**必須**有
`// [rev6-inline …] 原行: <example 那行原始內容>` 標記、且 `原行:` 後內容＝基線該行（正規化後相等）。
缺 → 紅、指名「檔:上游原行」。我方新檔／純新增行（example 沒有）不要求原行。

★補位（rev4:B-052）：新增型（基線沒有的新行）雖不要原行，但依 §III 須走「新增型圈界」rev6-inline
標記——`find_unmarked_additions` 補這道，令「所有 fork-delta（修改＋新增）皆帶 rev6-inline 標記、
上游 rebase 可定位」。機器生成檔（Generated by header）由重算保證 fork-delta、豁免手標。

★新檔面（002 刀 U0 fix 輪補；`docs/ops/reference-src/code-gate-contracts.md` §4「新增型缺圈界標記（本刀兩新檔）」、
spec FR-025／US6）：基線沒有的**整檔**（我方新檔）rev5 形整檔豁免——既不驗圈界也不驗授權，
兩腿對 002 刀唯一的 fork-delta 面（該刀 U3 兩支 base-web 新檔：T025 typings／T031 service wrapper；
U4 之 T035 續補 T031 該檔、不增新檔支數——該檔對基線恆為我方新檔、兩道判定照跑）覆蓋率為 0。改形＝新檔走兩道：
①檔頭圈界標記必在（憲法 §III「新增型…新檔僅檔頭一行標記」；限檔頭區、埋在檔中不算）且定形
　`[rev6-inline <軌道名>+ <刀名>]`——`+` 尾綴＝新增型、缺即紅指名（契約 §1.3；002 刀 U3 補）
②標記自稱 §III.1 軌道時、檔路徑須落該軌道範圍欄之新增面（[`S1_NEW_FILE_FACE`]）。名冊外之名
不做名冊斷言——§III.2 表外宣告 3 與 rev5:ADR 0021 款 1 明寫「純新增檔不觸 ★軌道、§III.1 三軌道表
＝常用新增面之預設清單、非新增面之窮舉排除」。生成檔仍豁免（同上一段）。

★掃描面（rev5:B-063）＝`src/` 之 .ts/.vue＋`build/` 之 .ts＋根層 `.env*`（`#` 註解前綴標記亦認——
rev4 舊面只掃 src/，`.env*` 與 build/ 的 fork-delta 全靠人工 review、upstream rebase 解錯不會紅）。
★授權判定（rev5:B-068）＝分層：§III.2 ★軌道驗（軌道×用途×檔案）三元組硬邊界、§III.1 三軌道
依範圍／紀律欄收窄檔面（ADAPT 修改型限根層 `.env*`；WRAPPER／RUSTAPI-SOURCE-ISOLATION 於
掃描面一律不可修改型）——rev4 舊判定只到軌道裸名，借一個在冊軌道名即可在無授權用途／檔上全綠。

每次執行**先跑 self-test**（合成缺原行/缺圈界樣本、證 lint 真能攔——防 vacuous 恆綠），無 `test` 時再跑實掃。
退出碼：0 綠／1 缺標記、缺原行或軌道外／2 結構斷言敗（名冊載入失敗、源倉缺席或未在 example、self-test 敗）／64 用法錯。
"""
import contextlib
import difflib
import io
import concurrent.futures
import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASEWEB = os.path.join(REPO, "base-web")
FORK = os.path.join(REPO, "fork260509-soybean-admin-base")
BASELINE = "example"
CONSTITUTION = os.path.join(REPO, ".specify", "memory", "constitution.md")
# §III.2 ★段零列時的合法態證據（憲法字面、strip 後全等；R10）——被移除即 die。
SENTINEL = "（空表——尚無 ★ 軌道；首列隨首刀 Amendment 落入。）"
USAGE = "用法：tools/fork-delta-lint.py [test] [--constitution <path>]"

MARKER = re.compile(r"原行:\s*(.*\S)\s*$")

# 軌道名＋用途抽取（rev5 T069②＋rev5:B-068；rev5:B-058 實測五種標記形都要吃）：group(1) 捕 `[rev6-inline`
# 後首個大寫 token——字元類止於 `(`（用途後綴）、`+`（新增型尾綴）、空白（刀號）與 `]`，
# 即恆為裸名、恰是名冊列的形（rev5:B-058：不剝就把合法標記整批誤判為名冊外）。group(2)（rev5:B-068 增）
# 捕選配用途後綴 `(a)`／`(i)`…的括號內識別符、無後綴＝None——三元組判定的第 2 維由此來。
# 五形＝`NAME+ 刀號`／`NAME(a) 刀號`／`NAME(i)`（無刀號）／`NAME 刀號`（.env 裸形）／
# 名冊側 `**`／`★` 裝飾（由 load_roster 剝）。
TRACK = re.compile(r"\[rev6-inline\s+([A-Z][A-Z0-9-]*)(?:\(([a-z]+)\))?")

# ★§III.1「範圍」欄字面對賬（002 刀 U0 fix 輪第 1 輪補）：鍵＝§III.1 表首欄字面、值＝該列範圍欄
# 之反引號 token **集**（以 [`_expand_range_files`] 抽取、與 §III.2 半邊共用同一支展開器）。
# ★比對以集合為之、次序不計（fix 輪第 3 輪校正）：下游（[`S1_NEW_FILE_FACE`] 的 lambda、§III.2 半邊
#   的 `files` 授權集）一律只做成員判定，token 在欄內的先後無語意。序敏感比對會對「兩 token 前後
#   對調」這種純排版 Amendment 擋下 commit，且訊息指向「lambda 須同批重導」的錯修法——誤報加誤導。
#   收窄／擴張／改名（真正會讓 lambda 失準的三形）在集合比對下照樣不等、照樣 die（RG21～RG23 釘住）。
# 為何非有不可：[`S1_NEW_FILE_FACE`] 的新增面判定是本檔寫死的 lambda，缺此對賬則走 §V.2 Amendment
# 收窄範圍欄（例：`src/service/api/rev6-*.ts` 改成 `…/rev6-settings.ts`）之後——軌道名集不變、
# s1_rows 仍恰 3、[`new_file_track_issue`] 的缺鍵 fail-loud 也不觸發——全鏈照綠，而 lambda 仍放行
# 整個舊面：**放寬**方向（over-permit）的靜默失準，正是 §III.2 半邊 RG8／RG9／RG11 三守
# 「檔級硬邊界不因憲法措辭而放寬」在 §III.1 半邊的同一失效類。
# ★RUSTAPI-SOURCE-ISOLATION 範圍欄「rust-api 整棵樹」無反引號 token＝空序；其新增面判定恆 False
#   （base-web 掃描面一律無授權、deny-all），放寬方向本就封死，空序是誠實值而非漏守。
S1_RANGE_LITERAL = {
    "BASE-WEB-ADAPT": (".env*", "src/typings/api/"),
    "BASE-WEB-WRAPPER": ("src/service/api/rev6-*.ts",),
    "RUSTAPI-SOURCE-ISOLATION": (),
}

# ★新檔標記之「軌道 × 檔路徑」判準（002 刀 U0 fix 輪）：鍵＝憲法 §III.1 表首欄字面、
# 值＝(該軌道新增面判定, 新增面描述)，判定逐字取自同表「範圍」欄——該「逐字取自」由
# [`S1_RANGE_LITERAL`] 於 [`load_roster`] 每次載入時機器對賬（見該常數註）、非僅口頭斷言。
# 射程界定：只在新檔檔頭標記**自稱**這三名時比對——名冊外之名不做名冊斷言（§III.2 表外宣告 3
# 「新增型 `NAME+` 標記不入名冊」＋rev5:ADR 0021 款 1「base-web 純新增檔不觸 ★軌道；§III.1
# 三軌道表＝常用新增面之預設清單、非新增面之窮舉排除」）。鍵集與 §III.1 三軌道名同步：在冊卻
# 無鍵＝憲法表被改名／增列、本判準已失準，於 [`new_file_track_issue`] fail-loud（不靜默放行）。
S1_NEW_FILE_FACE = {
    "BASE-WEB-ADAPT": (
        lambda rel: rel.startswith("src/typings/api/") or ("/" not in rel and rel.startswith(".env")),
        "`src/typings/api/` 新檔＋根層 `.env*`"),
    "BASE-WEB-WRAPPER": (
        lambda rel: rel.startswith("src/service/api/rev6-") and rel.endswith(".ts"),
        "`src/service/api/rev6-*.ts` 新檔（`rev6-` 前綴）"),
    "RUSTAPI-SOURCE-ISOLATION": (
        lambda rel: False,
        "rust-api 整棵樹（base-web 掃描面內一律無授權）"),
}


def die(msg):
    print(f"[fork-delta-lint] ✗ {msg}", file=sys.stderr)
    sys.exit(2)


def _expand_range_files(cell):
    """rev5:B-068：§III.2 範圍欄 → 授權檔案清單。抽反引號包的路徑（`／` 分隔符在反引號外、
    自然落掃描面外）；路徑內 brace 展開 `{a,b,c}`（單組足矣、殘留 brace 與非路徑 token
    由 load_roster 的殘渣斷言 die）。

    ★（…）注記**內**的反引號 token 一律不入集（rev5 確認輪補）：注記是說明性引用——含否定語境
    （「（不含 `src/x.ts`）」）——舊形照收＝檔級硬邊界被注記靜默放寬（實測 x.ts 直接進
    授權集）。span 判定在 cell 層、不觸及反引號**內**的全形括號（`src/a.ts（1 處）` 這種
    展開器壞掉殘渣仍完整進 token、由殘渣斷言 die——RG6 語意不變）。RG9 釘住。
    ★brace alt 與整段 token 皆 strip（rev5 確認輪補）：`{a, b}` 逗號後的裝飾空白舊形直接拼進
    路徑（`src/m/ b.ts`）＝合法授權檔靜默失真、誤報三元組第 3 維不合。RG11 釘住。
    ★殘留已知界線：**（…）之外**的路徑形否定措辭（裸寫「不含 `src/b.ts`」不加括號）仍會
    進集——語意判讀超出本工具射程；表注記恆用（…）括號、裸形由 review 兜底。"""
    spans = [(sm.start(), sm.end()) for sm in re.finditer(r"（[^）]*）", cell)]
    files = []
    for tok in re.finditer(r"`([^`]+)`", cell):
        if any(a <= tok.start() < b for a, b in spans):
            continue
        path = tok.group(1).strip()
        m = re.search(r"\{([^}]*)\}", path)
        if m:
            files += [path[:m.start()] + alt.strip() + path[m.end():]
                      for alt in m.group(1).split(",")]
        else:
            files.append(path)
    return files


def load_roster(path=CONSTITUTION):
    """rev5 T069①＋rev5:B-068 升維：授權名冊＝constitution §III.2 ★軌道 ∪ §III.1 三軌道，
    回 (s1, s2)——s1＝§III.1 三軌道名集（範圍非檔級名冊；修改型標記之檔面收窄判定
    在 [`find_rogue_tracks`]）；s2＝§III.2 ★軌道結構化名冊 {軌道: {用途識別符: 檔案集}}
    （授權單位＝三元組、檔級硬邊界＝表外宣告 1）。rev4 舊形只回裸名集＝借一個在冊軌道名即可
    在無授權用途／檔上開標記而全綠（rev5:B-068）。path 參數化（同 [`changed_files`] 之 B63f
    範式）＝讓 self-test 能以合成憲法片段走**同一條**真載入鏈、把各道表列形守釘住
    （守被無聲移除即測紅）；預設＝真 constitution、CLI `--constitution` 只供自身變異驗證。

    掃描錨（§III.2 自述）：表格資料列以 `|` 起、跳標題列與分隔列；軌道名於首欄、
    剝 `**` 與 `★` 裝飾。★檔缺席／掃空＝die（fail-loud，絕不默認空名冊放行一切）。
    結構斷言（每次執行都跑；承 rev5 T069⑤、rev6 R10 改形②）：①名冊整體非空②§III.2 ★段零列時
    MUST 命中哨兵句 SENTINEL（section 2 之非表列行、strip 後全等）、否則 ≥1 列；哨兵句與資料列並存
    ＝矛盾亦 die（首列落入時哨兵句須同批移除）③§III.1 恰 3 列④§III.2 表外宣告 2 明文「不另開軌道」
    之兩名不在冊⑤（rev5:B-068 增）每 ★ 列的用途識別符與檔案集不得為空、檔案集不得殘留 brace／
    全形括號、且每支須為路徑形（含 `/` 或根層 `.env*`——反引號包的裝飾性措辭不得靜默放寬檔級
    硬邊界；縮窄／放寬兩向皆 die 不靜默）⑥（002 刀 U0 fix 輪第 1 輪增）§III.1 實名列的範圍欄
    反引號 token 集須逐字＝[`S1_RANGE_LITERAL`]（次序不計——下游只做成員判定），不等即 die（[`S1_NEW_FILE_FACE`] 的 lambda
    與憲法字面脫節＝新檔腿按舊面放行；射程＝憲法實名列，合成憲法之化名列不做此對賬）。"""
    if not os.path.isfile(path):
        die(f"constitution 不存在：{path}（授權名冊來源、缺之即無授權判準）")
    s1, s2, s1_rows, s2_rows, section = set(), {}, 0, 0, None
    s1_face = {}                             # §III.1 軌道名 → 該列「範圍」欄原文（字面對賬用）
    sentinel_seen = False
    for line in open(path, encoding="utf-8").read().splitlines():
        if line.startswith("### III.1"):
            section = 1
            continue
        if line.startswith("### III.2"):
            section = 2
            continue
        if line.startswith(("## ", "### ")):
            section = None
            continue
        # ★縮排表列（rev5 fix 輪第 3 輪補）：markdown 允許表列前置最多 3 個空格、編輯器自動縮排
        #   或貼上極易產生；不 lstrip 即整列走 skip＝靜默漏收該用途——與下方續列守同一條
        #   skip、同一個後果，只是觸發手法從「省略重複欄值」換成「表格縮排」。lstrip 不影響
        #   cells 索引（split("|") 的 cells[0] 只是多含前置空白）。RG7 釘住（縮排列須載入為與
        #   未縮排完全相同的名冊）。
        if section is None:
            continue
        if not line.lstrip().startswith("|"):
            if section == 2 and line.strip() == SENTINEL:
                sentinel_seen = True          # rev6 空 ★表的合法態證據（R10）
                continue
            # ★缺行首 `|` 的表列（GFM 允許省略首尾 pipe；rev5 確認輪補）：手寫／貼上新列極易漏
            #   行首 pipe，走 skip＝整列靜默蒸發——與續列守／RG7 縮排守同病第三形。判準＝非 `|`
            #   起首卻含 ≥3 個 `|` 的行（本節散文至多單一反引號 `|` 字面、撞不到）；§III.1 由
            #   「恰 3 列」斷言接住、不需此守。RG10 釘住。
            if section == 2 and line.count("|") >= 3:
                die("§III.2 表出現缺行首 `|` 的表列（GFM 允許省略、本載入器不解讀）——"
                    "該列會靜默漏收整個用途；每列請以 `|` 起首完整書寫")
            continue
        cells = line.split("|")
        # 剝 `**`／`★` 裝飾之 strip 集含空白（rev5 fix 輪補）：`** ★NAME**`（粗體內側多一空格的
        # 裝飾性微調）在缺空白的 strip 集下名字殘留 `★`、s2 鍵變 `★NAME` ⇒ 合法標記誤報
        # 「軌道名不在授權名冊」——裝飾性微調不得產生誤導性紅。
        name = cells[1].strip().strip("*★ ") if len(cells) > 1 else ""
        # ★§III.2 續列守（rev5 fix 輪補）：首欄留空（markdown「省略重複欄值」的常見整理手法——
        # 同軌道名連續重複多列、正是會被順手美化的形）若走下方 skip＝靜默漏收整個用途；後果與
        # §III.1 列數斷言所修同病：合法標記誤報「用途不在集」並指向不必要的 Amendment、真病灶
        # （表列形被改）不被指出。§III.1 半邊由 s1_rows 恰 3 斷言接住、不需此守；不設 s2_rows
        # 精確值——§III.2 本就設計成隨 Amendment 增列，精確值會讓每次開新用途都要改工具。
        if section == 2 and not name:
            die("§III.2 表出現首欄留空的續列——本載入器逐列獨立解讀、續列會靜默漏收該用途；"
                "每列首欄須完整寫出 **★軌道名**、不可用省略重複欄值的表格整理手法")
        # 跳標題列（首欄「軌道」）與分隔列（純 -/: 字元）
        if not name or name == "軌道" or set(name) <= set("-: "):
            continue
        if section == 1:
            s1.add(name)
            s1_rows += 1
            s1_face[name] = cells[2] if len(cells) > 2 else ""
            continue
        s2_rows += 1
        m = re.match(r"\(([a-z]+)\)", cells[2].strip() if len(cells) > 2 else "")
        if not m:
            die(f"§III.2 ★軌道 {name} 列的用途欄抽不出括號識別符（(a)/(i)…）——"
                f"表列形被改動、三元組第 2 維無判準（升維非空斷言）")
        files = _expand_range_files(cells[3] if len(cells) > 3 else "")
        if not files:
            die(f"§III.2 ★軌道 {name}({m.group(1)}) 列的範圍欄抽不出任何反引號路徑——"
                f"表列形被改動、三元組第 3 維無判準（升維非空斷言）")
        for f in files:
            # ★路徑形狀判準（rev5 fix 輪第 3 輪補＋確認輪校準）：（…）注記**外**的反引號 token
            #   直接進檔案集——非路徑裝飾性措辭（裸寫「見 `translateBackendMsg`」）即靜默
            #   多出三元組、檔級硬邊界（§III.2 表外宣告 1）被無聲放寬。合法授權檔恆含 `/`
            #   或為根層 `.env*`，兩者皆非＝不是路徑、die。RG8 釘住。
            #   ★本守射程誠實界定：只擋「非路徑形」token 與殘渣。**路徑形**的否定措辭寫在
            #   （…）注記內＝已由 _expand_range_files 排除不入集（RG9）；裸寫在注記外＝
            #   仍會進集（語意判讀超出射程、見該函式 docstring 殘留界線句）——勿把本守讀成
            #   「放寬方向已全封」。
            if re.search(r"[{}（）]", f) or ("/" not in f and not f.startswith(".env")):
                die(f"§III.2 ★軌道 {name}({m.group(1)}) 範圍欄抽出殘渣／非路徑 token：{f}——"
                    f"殘留 brace／全形括號＝展開器壞掉、檔案集失真；無 `/` 又非根層 `.env*`＝"
                    f"反引號包的裝飾性措辭被當授權檔、檔級硬邊界靜默放寬"
                    f"（rev5:B-068 表外宣告 1；升維殘渣斷言）")
        s2.setdefault(name, {}).setdefault(m.group(1), set()).update(files)
    roster = s1 | set(s2)
    if not roster:
        die("名冊掃描為空——constitution §III.1/§III.2 表格錨可能被改動（非空斷言①）")
    # ★rev6 R10 改形：rev5「§III.2 ≥4 列」樓地板守的是「名冊被無聲移除」；rev6 憲法 §III.2 明寫空表為
    #   合法態、哨兵句就是「表為空是刻意的」證據——零列而無哨兵句＝表錨被改／名冊被無聲移除、die；
    #   哨兵句與資料列並存＝首列落入時忘了移除哨兵句、矛盾亦 die（守不消失、兩向皆非靜默）。
    if s2_rows == 0 and not sentinel_seen:
        die(f"§III.2 ★軌道表零列且未見哨兵句「{SENTINEL}」——表錨或列形被改動、或名冊被無聲移除"
            f"（rev6 空 ★表合法態的唯一證據＝哨兵句；research R10）")
    if s2_rows >= 1 and sentinel_seen:
        die(f"§III.2 ★軌道表掃得 {s2_rows} 列卻仍見哨兵句「{SENTINEL}」——空表哨兵與資料列並存＝矛盾"
            f"（首列隨 Amendment 落入時哨兵句須同批移除）")
    # ★§III.1 半邊的同形斷言（rev5 final holistic review 補：rev5 原三重斷言**全部只約束 §III.2**，
    #   §III.1 三軌道可靜默自名冊掉線而 lint 全綠）。失效鏈：把 `### III.1` 改成 `### III-1`
    #   （或整表刪除）⇒ roster 縮成 ★ 名集、輸出仍宣稱「軌道名皆在名冊」，直到某刀第一次用
    #   BASE-WEB-ADAPT／BASE-WEB-WRAPPER 開**修改型**標記才報「不在名冊、須先走 §V.2 Amendment」
    #   ——指向錯誤修法（該軌道早已授權），真病灶不被指出。與 pre-commit 把 constitution 納入
    #   fork-delta 觸發源所修的是同一個「fail-late 且誤導」病。
    if s1_rows != 3:
        die(f"§III.1 預設可動軌道表掃得 {s1_rows} 列（須恰 3）——表錨或列形被改動；名冊會靜默少收三名而全鏈照綠（非空斷言③）")
    # §III.2 表外宣告 2 明文：devproxy 由 §III.1 ADAPT 以根層 `.env*` 涵蓋、modal 治理隨頁面接線軌道承載
    # ——兩者**不另開軌道**；掃進名冊＝掃描面誤及散文或有人違宣告開列（rev5 承襲指針散文反例守、rev6 同義保留）。
    for absent in ("MODAL-WIRING", "BASE-WEB-DEVPROXY-WIRING"):
        if absent in roster:
            die(f"{absent} 被掃進名冊——§III.2 表外宣告 2 明文不另開此軌道，"
                f"掃描面誤及散文或違宣告開列＝名冊失真（反例斷言）")
    # ★§III.1 範圍欄字面對賬（斷言⑥；射程＝憲法實名列——合成憲法之化名列一名都不在鍵集即整段跳過，
    #   名冊守 RG1～RG19 的化名表因此不受影響）。實得 ≠ 期望即 die，兩種病灶同一道：①範圍欄內容被
    #   Amendment 改動（放寬／收窄皆然）②實名列被改名／移除而少收（此時 got 缺該鍵、亦不等）。
    if any(n in S1_RANGE_LITERAL for n in s1_face):
        got = {n: frozenset(_expand_range_files(c))
               for n, c in s1_face.items() if n in S1_RANGE_LITERAL}
        want = {n: frozenset(v) for n, v in S1_RANGE_LITERAL.items()}
        if got != want:
            bad = sorted(n for n in set(got) | set(want) if got.get(n) != want.get(n))
            # 訊息用：集合本身無序，逐名 sorted 後呈現（同一病灶每次輸出同一行、便於對賬）。
            got_shown = {n: sorted(got.get(n, ())) for n in bad}
            want_shown = {n: sorted(want.get(n, ())) for n in bad}
            die(f"§III.1 範圍欄字面與本工具 S1_RANGE_LITERAL 不符（不符軌道：{bad}）——"
                f"實得 {got_shown}／期望 {want_shown}；"
                f"憲法 §III.1 表已變更，S1_NEW_FILE_FACE 的新增面判定須同批重導，"
                f"否則新檔腿仍按舊面放行＝授權靜默放寬")
    return s1, s2


def find_rogue_tracks(rel, ours_content, s1, s2):
    """rev5 T069③＋rev5:B-068 升維：修改型標記（同行含 `原行:`）的授權判定，由軌道裸名升為分層判定
    ＋「同行必含 `[rev6-inline` token」強制（堵漏洞：任何含 `原行:` 的行都算已記錄）。
    分層（§III.2 表外宣告 1／3 與兩表語意）：
    · §III.1 三軌道（s1）＝範圍非檔級名冊，但**修改型**標記仍依範圍／紀律欄讀出檔面硬約束
      （rev5:B-068 殘留面第 2 輪收口）：ADAPT 修改型限根層 `.env*`（裸形、無用途後綴＝合法——
      範圍欄另一半 `src/typings/api/` 限**新檔**、新檔無基線不入修改型射程）；WRAPPER 紀律
      欄逐字「一律新檔…不改既有 service 檔」／RUSTAPI-SOURCE-ISOLATION 範圍欄逐字
      「rust-api 整棵樹」⇒ 兩名於 base-web 掃描面（＝upstream 既有檔）之修改型標記一律紅。
      ★ADAPT 修改型為何限根層 `.env*` 而非一律紅：rev6 憲法 §III.1 ADAPT 紀律欄逐字「新增為主；
      inline 修改限根層 `.env*` 接管面（§III.2 表外宣告 2 指定之 devproxy 涵蓋路徑）」——本判定
      與憲法字面一致（該字面於 rev5 憲法 v1.4.0 收斂、rev5:ADR 0040 款四／rev5:B-071；rev6 憲法
      直接承襲收斂後的形，不再有「工具寬鬆解 vs 憲法嚴字面」的張力）。
    · §III.2 ★軌道（s2）＝三元組硬邊界：①軌道在冊②用途後綴 ∈ 該軌道用途集（★修改型
      標記**無**用途後綴＝紅——無從驗授權單位）③所在檔 rel ∈ 該（軌道,用途）檔案集。
    回 ([(標記行去空白, 錯因)], 已檢查之修改型標記行數)。★射程僅修改型——新增型
    `NAME+` 不入三元組判定（§III.2 表外宣告 3、承 rev5:ADR 0021 款 1）。"""
    out, checked = [], 0
    for l in ours_content.splitlines():
        if "原行:" not in l:
            continue
        s = l.strip()
        if "[rev6-inline" not in s:
            out.append((s, "缺 [rev6-inline token——裸 `原行:` 不構成合法修改型標記"))
            continue
        checked += 1
        m = TRACK.search(s)
        if not m:
            out.append((s, "抽不出軌道名（標記形制不符 `[rev6-inline <TRACK>…]`）"))
            continue
        name, purpose = m.group(1), m.group(2)
        if name in s1:
            # rev5:B-068 殘留面收口：§III.1 軌道名不再是全域通行證（舊形＝借這 3 名到掃描面
            # 任一檔皆全綠）。s1 名單受 load_roster「恰 3 列」斷言凍結——Amendment 增列第 4 軌道
            # 時載入器先 die、本判定同步更新，不會靜默漏判。
            if name == "BASE-WEB-ADAPT" and "/" not in rel and rel.startswith(".env"):
                continue                     # ADAPT 修改型唯一合法面＝根層 `.env*`
            out.append((s, f"§III.1 軌道 {name} 之修改型標記在檔 {rel} 無授權"
                           f"（rev5:B-068 殘留面：ADAPT 修改型限根層 `.env*`；WRAPPER／"
                           f"RUSTAPI-SOURCE-ISOLATION 於 base-web 既有檔無修改型授權）"))
            continue
        if name not in s2:
            out.append((s, f"軌道名 {name} 不在授權名冊（constitution §III.1/§III.2）"))
        elif purpose is None:
            out.append((s, f"★軌道 {name} 修改型標記無用途後綴——無從驗授權單位"
                           f"（rev5:B-068；§III.2 授權單位＝軌道×用途×檔案三元組）"))
        elif purpose not in s2[name]:
            out.append((s, f"用途 ({purpose}) 不在 ★軌道 {name} 用途集"
                           f" {{{'、'.join('(' + p + ')' for p in sorted(s2[name]))}}}"
                           f"（rev5:B-068 三元組第 2 維不合；未列用途不因軌道已開而自動授權）"))
        elif rel not in s2[name][purpose]:
            out.append((s, f"檔 {rel} 不在 ★軌道 {name}({purpose}) 授權檔案集"
                           f"（rev5:B-068 三元組第 3 維不合；檔級名單＝硬邊界、§III.2 表外宣告 1）"))
    return out, checked


def sh(args, cwd):
    # 清掉 GIT_* env：git hook 會把外層 repo 的 GIT_DIR/GIT_INDEX_FILE 洩漏給子行程，
    # 害對 base-web worktree（.git 為檔）跑 git 抓錯 index（.git/index: Not a directory）。
    env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
    return subprocess.run(args, cwd=cwd, capture_output=True, text=True, env=env)


def is_code(line):
    s = line.strip()
    return bool(s) and not s.startswith(("//", "/*", "*", "<!--"))


def norm(line):
    # 去尾端逗號/分號：加新同層條目使前一行多尾逗號，屬新增型副作用、非語意改變（§III「語意被改變」才算修改型）
    return line.strip().rstrip(",;").rstrip()


def find_missing(base_content, ours_content):
    """回傳「基線有、我方既無此行、又無對應原行標記」的上游**原行**（供逐字補回）。
    ★比對用 norm（去尾標點）、輸出保原行原貌（含尾逗號等）。"""
    ours = ours_content.splitlines()
    ours_lines = {norm(l) for l in ours}
    recorded = set()
    for l in ours:
        if "[rev6-inline" not in l:
            continue  # rev5 T069③：裸 `原行:`（無 rev6-inline token）不算已記錄——防形制外洗白
        m = MARKER.search(l)
        if m:
            val = m.group(1)
            # ★註解收尾 token 不入原行值（spec-compliance-003 L4-2）：`.vue` template 形 `<!-- [...] 原行: <基線該行> -->`／塊註解形
            #   `/* [...] 原行: … */` 之行尾 `-->`／`*/` 屬標記自身；只在標記行以同族開頭起首時剝一次，`//` 標記之原行尾端照原樣比對。
            head = l.lstrip()
            for opener, closer in (("<!--", "-->"), ("/*", "*/")):
                if head.startswith(opener) and val.endswith(closer):
                    val = val[: -len(closer)].rstrip()
                    break
            recorded.add(norm(val))
    seen = set()
    missing = []
    for raw in base_content.splitlines():
        if not is_code(raw):
            continue
        n = norm(raw)
        if not n or n in ours_lines or n in recorded or n in seen:
            continue
        seen.add(n)
        missing.append(raw.strip())  # 原行原貌（去首尾空白、保尾逗號）
    return missing


def is_generated(content):
    """檔頭 8 行含生成器標記＝機器生成檔（elegant-router／unplugin 等）：fork-delta 由重算保證、
    不手標圈界，故豁免（憲法 §III 生成檔紀律之機器承載）。★限檔頭（避免誤中 hand-written 檔散文裡的
    『auto generated』字樣——upstream example tip 之 store/modules/route/index.ts、theme/shared.ts 散文即有）。"""
    head = "\n".join(content.splitlines()[:8])
    return bool(re.search(r"Generated by|@generated", head))


def _code_of_line(line, closing):
    """單行去註解：回（碼文本, 新 closing 態）。`closing`＝跨行區塊註解的待閉合 token
    （None＝不在註解內）。★逐字元掃描、正確處理跨行 /* */、<!-- --> 之開閉——含『同行
    閉合後緊接碼』（rev5 對抗驗證 NF-A：`*/ code` 不再整行丟棄）與『同行連續 /* */ /* …』
    （rev5 對抗驗證 NF-C：第二註解 body 不洩為碼）；行註解 // 到行尾（不跨行、closing 不置位）。
    唯一消費者＝[`_block_code_added`]（新增型圈界掃描）——去註解規則只此一處（rev5 曾與語意守
    共用，002 刀 U0 隨三組語意守移除後只剩此面）。已知界線：不解析字串常值、字串內的 `/*` 會被當註解起首。"""
    rest, code = line, ""
    while rest:
        if closing:                          # 在跨行區塊註解內、找閉合
            k = rest.find(closing)
            if k < 0:
                return code, closing
            rest, closing = rest[k + len(closing):], None
            continue
        cands = [(rest.find(t), t) for t in ("//", "/*", "<!--") if t in rest]
        if not cands:
            return code + rest, None
        i, t = min(cands)
        code += rest[:i]
        if t == "//":
            return code, None                # 行註解到行尾
        closing, rest = ("*/" if t == "/*" else "-->"), rest[i + len(t):]
    return code, closing


def _block_code_added(added):
    """回 added 各『去註解後仍有實質碼』的行（原行原貌）。去註解規則見 [`_code_of_line`]。"""
    out, closing = [], None
    for l in added:
        code, closing = _code_of_line(l, closing)
        if code.strip():
            out.append(l)
    return out


def _structural_only(line):
    """純結構標點行（}、);、],… 無任何識別碼字元）＝區塊延續、不需獨立圈界（避免對閉合括號誤報）。"""
    return not re.search(r"[0-9A-Za-z_$]", line)


def _block_has_marker(added):
    """change-block 內有無合法 rev6 標記——限『註解行』且含 [rev6-inline（排除字串常值內同名子字串
    的自我認證：rev5 對抗驗證 FN2）。`#` 臂＝`.env*` 之註解形（rev5:B-063：ADAPT 標記為 `# [rev6-inline …]`
    裸形）、判準收窄為「去 `#` 與空白後**緊接** `[rev6-inline`」：`#` 在 .ts 是合法識別字起首
    （private field），寬形（起首 `#` 且行內任處含 token）會讓 `#tag = 'x [rev6-inline] y';`
    自我認證整個新增塊＝FN2 在 `#` 臂重開（self-test B63g 釘住）。"""
    for s in (l.strip() for l in added):
        if s.startswith(("//", "/*", "*", "<!--")) and "[rev6-inline" in s:
            return True
        if s.startswith("#") and s.lstrip("#").lstrip().startswith("[rev6-inline"):
            return True
    return False


def find_unmarked_additions(base_content, ours_content):
    """回「新增碼 change-block 卻無合法 rev6-inline 標記」之首個實質新增行（供補圈界標記）。★補位
    find_missing（後者驗修改型缺原行）；本函式驗新增型缺圈界，合起來令所有 fork-delta 皆帶標記。
    §III 新增型圈界紀律。

    以 difflib.unified_diff 取差異、按 **change-block**（連續 +/- 行為一塊、context 行〔含空白〕分界）；
    ★只驗『純新增塊』（塊內無任何被移除碼行）——含被移除碼行者＝修改型/替換區塊、由 find_missing
    驗原行、本函式跳過（故 rev5 captcha 型『替換邏輯與其原行標記被空白 context 分隔』不誤報）。純新增塊去
    （跨行）註解＋純結構標點行（閉合 } 等＝區塊延續）後仍有實質新增碼卻無合法標記（限註解行、字串
    常值內子字串不算）→報首行。分工：修改型缺原行→find_missing；純新增（新 import/欄位）缺圈界→本函式。
    ★已知可接受殘留（rev5 兩輪對抗驗證後定）：①與修改型同塊（無 context 分隔）的額外未圈界新增歸該塊
    原行標記涵蓋、不另報（修它會重引入 captcha 型替換誤報張力）；②字串常值內未閉合 /* 之後續行罕見被當
    註解（窄 FN；不做 string-parsing）。假 DEL 洗白被 find_missing『刪行缺原行』兜住。"""
    out = []
    added, removed = [], []
    seen_hunk = False

    def flush():
        if any(is_code(l) for l in removed):
            return                           # 修改型/替換塊（含移除碼）→ 歸 find_missing、本函式跳過
        substantive = [l for l in _block_code_added(added) if not _structural_only(l)]
        if substantive and not _block_has_marker(added):
            out.append(substantive[0].strip())

    for line in difflib.unified_diff(base_content.splitlines(),
                                     ours_content.splitlines(), n=3, lineterm=""):
        if line.startswith("@@"):
            flush(); added, removed = [], []; seen_hunk = True
        elif not seen_hunk:
            continue                         # unified_diff 檔頭 ---/+++（首個 @@ 前）——seen_hunk 旗標
        elif line.startswith("+"):           # 認檔頭，內容以 ++/-- 起首不撞 +++/---（rev5 對抗驗證 INT1）
            added.append(line[1:])
        elif line.startswith("-"):
            removed.append(line[1:])
        else:                                # context 行（含空白）＝ change-block 分界
            flush(); added, removed = [], []
    flush()
    return out


def _first_substantive(content):
    """檔內首個「去註解後仍有實質碼」且非純結構標點的行（供新檔缺標記訊息指位）。
    去註解與結構標點規則沿用 [`_block_code_added`]／[`_structural_only`]、不另立第二套。"""
    for l in _block_code_added(content.splitlines()):
        if not _structural_only(l):
            return l.strip()
    return ""


def find_new_file_marker(content):
    """我方新檔的**檔頭**圈界標記行（憲法 §III「新增型…新檔僅檔頭一行標記」）；無＝None。
    檔頭區＝首個實質碼行之前的空白／註解行；標記埋在該行之後不算——否則「新檔僅檔頭一行」
    退化成「檔內任處有 token 即可」（與 [`_block_has_marker`] 對整塊搜尋的語意差別即此守）。
    標記認得形沿用 [`_block_has_marker`]（含 `.env*` 的 `#` 臂與字串常值自證防線）。"""
    for line in content.splitlines():
        s = line.strip()
        if not s or s.startswith(("//", "/*", "*", "<!--", "#")):
            if _block_has_marker([line]):
                return s
            continue
        return None                          # 首個實質碼行——檔頭區到此為止
    return None                              # 全檔皆空白／註解且無標記


def new_file_track_issue(rel, marker, s1):
    """新檔檔頭標記的「定形 × 軌道 × 檔路徑」判定（`docs/ops/reference-src/code-gate-contracts.md` §4「新增檔標記所稱軌道與
    檔路徑不符＝紅」＋「`+` 尾綴＝新增型」）：回錯因字串、合格回 None。定形＝軌道名後緊接 `+`（002 刀 U3 補）；
    軌道射程＝標記自稱 §III.1 三軌道時比對 [`S1_NEW_FILE_FACE`]；名冊外之名不做名冊斷言（§III.2 表外宣告 3、rev5:ADR 0021 款 1——
    純新增檔本就不觸 ★軌道，於此報「不在名冊」即與憲法字面相衝）。"""
    m = TRACK.search(marker)
    if not m:
        return "檔頭標記抽不出軌道名（形制須為 `[rev6-inline <軌道名>+ <刀名>] <一句話理由>`）"
    name = m.group(1)
    # ★`+` 尾綴定形（002 刀 U3 補；`docs/ops/reference-src/code-gate-contracts.md` §4「`+` 尾綴＝新增型」）：軌道名後須**緊接**
    #   `+`——`NAME 刀名`（.env 修改型裸形）／`NAME(a) 刀名`（★軌道修改型用途形）皆非新檔形、缺即紅。
    #   置於名冊判定之前：形制約束對名冊外之名同樣成立（§III.2 表外宣告 3 的新增型形本就是 `NAME+`）。
    if marker[m.end(1):m.end(1) + 1] != "+":
        return (f"檔頭標記缺新增型 `+` 尾綴（軌道名 {name} 後須緊接 `+`；契約定形 "
                f"`[rev6-inline <軌道名>+ <刀名>] <一句話理由>`、`docs/ops/reference-src/code-gate-contracts.md` §4）")
    if name not in s1:
        return None                          # §III.1 外之名：不做名冊斷言（rev5:ADR 0021 款 1）
    if name not in S1_NEW_FILE_FACE:
        return (f"§III.1 軌道 {name} 在冊卻無對應新增面判準——憲法 §III.1 表被改名／增列、"
                f"本工具 S1_NEW_FILE_FACE 已失準（fail-loud、不靜默放行）")
    ok, face = S1_NEW_FILE_FACE[name]
    if ok(rel):
        return None
    return (f"新檔標記自稱 §III.1 軌道 {name}、但檔不在其範圍欄新增面 {face}"
            f"（憲法 §III.1 範圍欄；軌道與檔路徑不符）")


def _parse_args(args):
    """CLI 引數 → (test_only, constitution_path)；用法錯回 None（呼叫端印 USAGE、rc 64）。
    `test`＝只跑 self-test（離線、不掃 base-web、不碰源倉）；`--constitution <path>`＝load_roster 的
    path（只供自身變異驗證）；無引數＝self-test＋全掃（rev5 形不變）。"""
    test_only, constitution, i = False, CONSTITUTION, 0
    while i < len(args):
        a = args[i]
        if a == "test":
            test_only = True
        elif a == "--constitution":
            if i + 1 >= len(args):
                return None
            constitution = args[i + 1]
            i += 1
        elif a.startswith("--constitution="):
            constitution = a.split("=", 1)[1]
        else:
            return None
        i += 1
    return test_only, constitution


def floor_violation(checked_total):
    """修改型樓地板守（spec-compliance-003 L4-4；復 rev5「真 repo 修改型 ≥1 處」之 die）：base-web 自 003 刀起帶修改型 inline，
    實掃 0 處＝掃描面塌縮（工作樹切離 rev6 分支、掃描根或副檔名收窄壞掉）或標記整批遺失，不得回綠。回錯因字串或 None。"""
    if checked_total < 1:
        return "修改型 0 處——base-web 自 003 刀起帶修改型 inline、實掃為零＝掃描面塌縮或標記整批遺失（查 base-web 分支與 changed_files 掃描面）"
    return None


def self_test():
    base = "  content: response.data.msg,\n  other: keep,\n"
    bad = "  content: $t(x),\n  other: keep,\n"  # 改了 content、無原行 → 須攔
    # ★rev5 T069④：修改型樣本的軌道名一律用名冊內實名（rev4 原用 I18N-WIRING／UI／DEP 等名冊外短名
    #   ——名冊斷言進場後，樣本自身就得是合規形，成對反例另列於下）。樣本軌道名為合成名冊 t_s2 之名、
    #   不讀真憲法；與 rev6 憲法 §III.2 現表之 BASE-WEB-I18N-WIRING(i) 同名無害＝刻意複用而非隔離。
    good = (
        "  // [rev6-inline BASE-WEB-I18N-WIRING(i)] 原行: content: response.data.msg,\n"
        "  content: $t(x),\n  other: keep,\n"
    )
    added = "  content: response.data.msg,\n  other: keep,\n  brandNew: 1,\n"  # 純新增、基線行未動
    assert find_missing(base, bad) == ["content: response.data.msg,"], "self-test A：應攔缺原行"
    assert find_missing(base, good) == [], "self-test B：有原行須過"
    assert find_missing(base, added) == [], "self-test C：純新增不誤判（find_missing 不管新增）"
    assert find_missing(base, bad + "brandNew: 1,\n") == ["content: response.data.msg,"], "self-test D：改+新增混合仍攔改的"
    # spec-compliance-003 L4-2：`.vue` template 修改型標記之行尾 `-->` 不入原行值——單行 HTML 註解形須過、原行值與基線不符仍攔。
    tbase = "<template>\n  <div class=x>\n</template>\n"
    tmark = "  <!-- [rev6-inline BASE-WEB-LOGIN-CAPTCHA-WIRING(i) 003-auth-session] 原行: {} -->\n"
    assert find_missing(tbase, "<template>\n" + tmark.format("<div class=x>") + "  <div class=y>\n</template>\n") == [], \
        "self-test D2：template 單行 HTML 註解形修改型標記須過（行尾 --> 不入原行值）"
    assert find_missing(tbase, "<template>\n" + tmark.format("<div class=z>") + "  <div class=y>\n</template>\n") == ["<div class=x>"], \
        "self-test D3：template 形原行值與基線不符仍須攔"
    # spec-compliance-003 L4-4：修改型樓地板守——0 處須回錯因、≥1 處放行。
    assert floor_violation(0) and floor_violation(19) is None, "self-test FL：修改型 0 處須 die、≥1 處放行"

    # 補位 find_unmarked_additions（新增型圈界覆蓋；rev4:B-052）：
    marked_add = "  content: response.data.msg,\n  other: keep,\n  // [rev6-inline I18N-WIRING(ii)] 新鍵\n  brandNew: 1,\n"
    block_add = ("  content: response.data.msg,\n  other: keep,\n"
                 "  // [rev6-inline I18N-WIRING(ii) START] 區塊\n  a: 1,\n  b: 2,\n"
                 "  // [rev6-inline I18N-WIRING(ii) END]\n")
    comma_only = "  content: response.data.msg\n  other: keep,\n"     # 純去尾逗號、norm 相等
    # ★大寫 Generated by 落第 9 行（檔頭 8 行外）——令 head-limit 版該回 False、全檔搜尋版該回 True，
    #   K 才非 vacuous（rev5 對抗驗證 INT2：原用小寫字樣、大小寫敏感致兩版皆過、擋不住退化）。
    non_gen = "".join("import x from 'y';\n" for _ in range(8)) + "// routes Generated by a plugin\n"
    assert find_unmarked_additions(base, added) == ["brandNew: 1,"], "self-test E：純新增無圈界標記須攔"
    assert find_unmarked_additions(base, marked_add) == [], "self-test F：新增帶圈界標記須過"
    assert find_unmarked_additions(base, block_add) == [], "self-test G：START/END 圈界 block 須過"
    assert find_unmarked_additions(base, comma_only) == [], "self-test H：純尾標點差非新增、不誤判"
    assert find_unmarked_additions(base, good) == [], "self-test I：修改型帶原行標記、additive 檢查不誤報"
    assert is_generated("/* eslint-disable */\n// Generated by elegant-router\nx\n"), "self-test J：生成檔 header 須識別"
    assert not is_generated(non_gen), "self-test K：Generated by 於第 9 行（檔頭 8 行外）不豁免"

    # rev5 對抗驗證修復回歸（change-block 級／區塊註解／結構豁免／標記限註解／++ 前綴）：
    b2 = "const o = {\n  title: 'Old',\n  keep1: 1,\n  keep2: 2,\n  keep3: 3,\n};\n"
    fn1 = ("const o = {\n  // [rev6-inline BASE-WEB-AUTH-WIRING(a) 002-system-settings] 原行: title: 'Old',\n  title: 'New',\n"
           "  keep1: 1,\n  newField: 9,\n  keep2: 2,\n  keep3: 3,\n};\n")
    struct = "function f() {\n  a();\n}\n"
    struct2 = "function f() {\n  // [rev6-inline X] guard\n  if (g) {\n  a();\n  }\n}\n"
    vbase = "<template>\n  <div>x</div>\n</template>\n"
    vadd = "<template>\n  <div>x</div>\n  <!--\n    multi line\n    comment\n  -->\n</template>\n"
    tbase = "const a = 1;\nconst b = 2;\n"
    tadd = "const a = 1;\n/*\nplain block comment\nline two\n*/\nconst b = 2;\n"
    sadd = 'a();\nlog("[rev6-inline] fake");\nb();\n'
    iadd = "let x = 1;\n++counter;\n"
    assert find_unmarked_additions(b2, fn1) == ["newField: 9,"], "self-test L：鄰近標記的未圈界實質新增仍須攔（FN1）"
    assert find_unmarked_additions(struct, struct2) == [], "self-test M：純結構標點新增（閉合 }）豁免、不誤報"
    assert find_unmarked_additions(vbase, vadd) == [], "self-test N：多行 HTML 區塊註解新增不誤報（FP1）"
    assert find_unmarked_additions(tbase, tadd) == [], "self-test O：多行 /* */ 純文字註解新增不誤報（FP2）"
    assert find_unmarked_additions("a();\nb();\n", sadd) == ['log("[rev6-inline] fake");'], "self-test P：字串內 [rev6-inline 非標記（FN2）"
    assert find_unmarked_additions("let x = 1;\n", iadd) == ["++counter;"], "self-test Q：++ 起首新增不因 +++ 前綴漏放（INT1）"
    # rev5 第二輪對抗驗證新缺陷回歸（NF-A 同行閉合後碼／NF-B 空白鄰接獨立純新增／NF-C 同行連續 /* */）：
    nfb_base = "import foo from 'a';\n\nrun();\n"
    nfb = ("// [rev6-inline BASE-WEB-ADAPT 002-system-settings] 原行: import foo from 'a';\nimport foo from 'b';\n"
           "\nimport brandNew from 'c';\nrun();\n")
    nfa_base = "const o = {\n  a: 1,\n};\n"
    nfa = "const o = {\n  a: 1,\n  /* note\n     line\n  */ newFlag: true,\n};\n"
    nfc = "const a = 1;\n/* first */ /* second\n   inside\n*/\nconst b = 2;\n"
    assert find_unmarked_additions(nfb_base, nfb) == ["import brandNew from 'c';"], "self-test R：獨立純新增（空白鄰接標記修改）仍須攔（NF-B）"
    assert find_unmarked_additions(nfa_base, nfa) == ["*/ newFlag: true,"], "self-test S：區塊註解同行閉合後的新碼須被攔（NF-A）"
    assert find_unmarked_additions("const a = 1;\nconst b = 2;\n", nfc) == [], "self-test T：同行連續 /* */ /* 之第二註解 body 不誤報（NF-C）"

    # ── rev5 T069②：軌道名＋用途抽取正則——rev5:B-058 實測五種標記形逐形釘住（rev5:B-068 增驗 group(2)）──
    #    含 rev6 契約定形之新檔檔頭形 `NAME+ 002-system-settings`（軌道名 ∈ §III.1 表首欄字面）。
    five_forms = [
        ("// [rev6-inline BASE-WEB-AUTH-WIRING(c)+ 002-system-settings] 圈界", "BASE-WEB-AUTH-WIRING", "c"),
        ("// [rev6-inline BASE-WEB-AUTH-WIRING(a) 002-system-settings] 原行: y", "BASE-WEB-AUTH-WIRING", "a"),
        ("// [rev6-inline BASE-WEB-LOGOUT-UX-WIRING(i)] 原行: y", "BASE-WEB-LOGOUT-UX-WIRING", "i"),
        ("# [rev6-inline BASE-WEB-ADAPT 002-system-settings] .env 裸形", "BASE-WEB-ADAPT", None),
        ("// [rev6-inline BASE-WEB-WRAPPER+ 002-system-settings] 新檔頭", "BASE-WEB-WRAPPER", None),
    ]
    for line, want, want_p in five_forms:
        m = TRACK.search(line)
        assert m and m.group(1) == want and m.group(2) == want_p, \
            f"self-test U：五形抽取失準（{line!r} 應得 {want}/{want_p}、實得 {m and m.groups()}）"
    assert TRACK.search("// [rev5-inline BASE-WEB-ADAPT+ 002-system-settings] 舊 token") is None, \
        "self-test U2：rev5 token `rev5-inline` 不得被當合法 rev6 標記（token 換世代之非 vacuous 證）"

    # ── rev5 T069③④⑤＋rev5:B-068：分層授權判定成對樣本（三元組合規過／各維不合攔）──────────
    #    合成名冊形＝load_roster 升維後的回傳形：(s1 軌道級名集, s2 三元組結構)。
    t_s1 = {"BASE-WEB-ADAPT", "BASE-WEB-WRAPPER", "RUSTAPI-SOURCE-ISOLATION"}
    t_s2 = {"BASE-WEB-I18N-WIRING": {"i": {"src/service/request/index.ts"}},
            "BASE-WEB-AUTH-WIRING": {"a": {"src/store/modules/route/index.ts"}}}
    env_mod = ("# [rev6-inline BASE-WEB-ADAPT 002-system-settings] 原行: VITE_X=static\n"
               "VITE_X=dynamic\n")
    for name, rel, sample in (("B", "src/service/request/index.ts", good),
                              ("L", "src/store/modules/route/index.ts", fn1),
                              ("R", ".env", env_mod)):
        rogue, checked = find_rogue_tracks(rel, sample, t_s1, t_s2)
        assert rogue == [] and checked >= 1, f"self-test V：授權合規修改型樣本 {name} 須過且被計數（實得 {rogue}／checked={checked}）"
    # V 樣本 B＝★軌道三元組全合規（rev5:B-068 DoD ③）；R＝§III.1 軌道（BASE-WEB-ADAPT）修改型
    # 之唯一合法面＝根層 `.env*`（裸形、無用途後綴；rev5 真 repo 4 處 .env 標記同形）。
    # 以下 B68f/g/h＝§III.1 借名反例（rev5:B-068 殘留面第 2 輪收口：舊形這 3 名在掃描面任一檔
    # 皆全綠——§III.1 紀律／範圍欄逐字讀出的檔面約束由此釘住）：
    for tag, nm, brl in (("B68f", "BASE-WEB-ADAPT", "src/store/modules/theme/index.ts"),
                         ("B68g", "BASE-WEB-WRAPPER", "src/service/api/auth.ts"),
                         ("B68h", "RUSTAPI-SOURCE-ISOLATION", "src/views/home/index.vue")):
        rogue, checked = find_rogue_tracks(
            brl, f"  // [rev6-inline {nm} 002-system-settings] 原行: title: 'Old',\n  title: 'New',\n",
            t_s1, t_s2)
        assert len(rogue) == 1 and "§III.1" in rogue[0][1] and checked == 1, \
            f"self-test {tag}：借 §III.1 軌道名 {nm} 到無授權檔 {brl} 須攔（實得 {rogue}）"
    # 以下三支＝★軌道三元組各維反例：
    rogue, checked = find_rogue_tracks("src/store/modules/auth/index.ts", good, t_s1, t_s2)
    assert len(rogue) == 1 and "第 3 維" in rogue[0][1] and checked == 1, \
        f"self-test B68a：在冊軌道＋在冊用途＋未授權檔須攔且指名第 3 維（rev5:B-068 反例①；實得 {rogue}）"
    rogue, checked = find_rogue_tracks(
        "src/service/request/index.ts",
        "  // [rev6-inline BASE-WEB-I18N-WIRING(ii)] 原行: title: 'Old',\n  title: 'New',\n",
        t_s1, t_s2)
    assert len(rogue) == 1 and "第 2 維" in rogue[0][1] and checked == 1, \
        f"self-test B68b：在冊軌道＋未列用途須攔且指名第 2 維（rev5:B-068 反例②；實得 {rogue}）"
    rogue, checked = find_rogue_tracks(
        "src/service/request/index.ts",
        "  // [rev6-inline BASE-WEB-I18N-WIRING] 原行: title: 'Old',\n  title: 'New',\n",
        t_s1, t_s2)
    assert len(rogue) == 1 and "無用途後綴" in rogue[0][1] and checked == 1, \
        f"self-test B68c：★軌道修改型標記無用途後綴須攔（無從驗授權單位；實得 {rogue}）"
    # ── rev5:B-068：範圍欄展開器——brace 展開＋`／` 分隔多檔＋（…）注記忽略，逐形釘住 ──
    assert _expand_range_files(
        "`src/views/_builtin/login/modules/{code-login,register,reset-pwd}.vue`（各 2 處，修改型）") == [
        "src/views/_builtin/login/modules/code-login.vue",
        "src/views/_builtin/login/modules/register.vue",
        "src/views/_builtin/login/modules/reset-pwd.vue"], \
        "self-test B68d：brace 展開失準（rev5:B-068 DoD 變異③的鑑別測）"
    assert _expand_range_files("`a.ts`（修改型）／`b.vue`（修改型＋新增型）") == ["a.ts", "b.vue"], \
        "self-test B68e：`／` 分隔多檔＋（…）注記忽略失準"
    rogue, checked = find_rogue_tracks(
        "src/x.ts", "  // [rev6-inline NOT-IN-ROSTER(i)] 原行: title: 'Old',\n  title: 'New',\n",
        t_s1, t_s2)
    assert len(rogue) == 1 and "NOT-IN-ROSTER" in rogue[0][1] and checked == 1, \
        f"self-test W：名冊外軌道名須攔且指名（實得 {rogue}）"
    rogue, checked = find_rogue_tracks(
        "src/x.ts", "  // 原行: content: response.data.msg,\n  content: $t(x),\n", t_s1, t_s2)
    # ★錯因斷「前綴相等」而非「含 `[rev6-inline` 子字串」＋併斷 checked==0：另一條錯因字面
    #   「抽不出軌道名（標記形制不符 `[rev6-inline <TRACK>…]`）」本身就含該子字串，舊斷法
    #   兩條腿都過＝vacuous——rev5 實測把 token 強制那段整個刪掉後 self-test 與實掃仍全綠（變異 A2
    #   為 21 支變異中唯一漏網者）。checked 亦可區分：正解版對裸 `原行:` 回 0、變異版回 1。
    assert len(rogue) == 1 and rogue[0][1].startswith("缺 [rev6-inline token") and checked == 0, \
        f"self-test X：裸 `原行:`（無 token）須落『缺 token』分支且不入 checked（實得 {rogue}／checked={checked}）"
    for bad_form in ("  // [rev6-inline] 原行: title: 'Old',\n  title: 'New',\n",
                     "  // [rev6-inline lower(i)] 原行: title: 'Old',\n  title: 'New',\n"):
        rogue, checked = find_rogue_tracks("src/x.ts", bad_form, t_s1, t_s2)
        assert len(rogue) == 1 and rogue[0][1].startswith("抽不出軌道名") and checked == 1, \
            f"self-test X3：有 token 但抽不出軌道名須落該分支且計入 checked（實得 {rogue}／checked={checked}）"
    bare = "  // 原行: content: response.data.msg,\n  content: $t(x),\n  other: keep,\n"
    assert find_missing(base, bare) == ["content: response.data.msg,"], \
        "self-test X2：裸 `原行:` 不算已記錄——find_missing 仍須攔缺原行（rev5 T069③ 堵洗白）"
    rogue, checked = find_rogue_tracks("src/x.ts", marked_add, t_s1, t_s2)
    assert rogue == [] and checked == 0, \
        f"self-test Y：新增型標記（無 `原行:`）不入三元組射程（§III.2 表外宣告 3；實得 {rogue}／checked={checked}）"

    # ── rev5:B-063：`.env*`（`#` 註解前綴）與 build/ 檔的紀律覆蓋——行級 diff 對語言無感，
    #    find_missing 對 `#` 標記本來就通（MARKER／recorded 不看註解前綴）；不通的只有
    #    find_unmarked_additions 的 `_block_has_marker`（原本僅認 //、/*、*、<!--），該處已擴 `#`。
    env_base = "# auth route mode\nVITE_X=static\n"
    env_bad = "# auth route mode\nVITE_X=dynamic\n"
    env_good = ("# auth route mode\n"
                "# [rev6-inline BASE-WEB-ADAPT 002-system-settings] 原行: VITE_X=static\n"
                "VITE_X=dynamic\n")
    assert find_missing(env_base, env_bad) == ["VITE_X=static"], \
        "self-test B63a：.env 動基線行無標記須攔（rev5:B-063 反例①）"
    assert find_missing(env_base, env_good) == [], \
        "self-test B63b：.env 帶 `#` 前綴原行標記須過（rev5 現存 4 處 .env 標記同形）"
    env_addb = env_base + "VITE_NEW=1\n"
    env_addm = env_base + "# [rev6-inline BASE-WEB-ADAPT+ 002-system-settings] 新增\nVITE_NEW=1\n"
    assert find_unmarked_additions(env_base, env_addb) == ["VITE_NEW=1"], \
        "self-test B63c：.env 純新增無圈界標記須攔"
    assert find_unmarked_additions(env_base, env_addm) == [], \
        "self-test B63d：.env `#` 前綴圈界標記須被認得（_block_has_marker 擴 # 的非 vacuous 證）"
    # ★B63d 的成對反例（rev5 fix 輪第 2 輪）：`#` 在 .ts 是合法識別字起首（private field）——
    #   寬形 `#` 臂（起首 `#` 且行內任處含 token）令字串常值 `'x [rev6-inline] y'` 自我認證
    #   整個新增塊（FN2 在 `#` 臂重開、self-test P 擋不到 `#` 起首形）；缺此反例則 `#` 臂
    #   只有正例、收窄被無聲放寬仍全綠。
    ts_priv = "class A {\n  #tag = 'x [rev6-inline] y';\n  #secret = 42;\n}\n"
    assert find_unmarked_additions("class A {\n}\n", ts_priv) == ["#tag = 'x [rev6-inline] y';"], \
        "self-test B63g：.ts 私有欄位行含 [rev6-inline 字串常值不得自證整塊（`#` 臂 FN2 反例）"
    build_base = "export const proxy = { enable: true };\n"
    build_bad = "export const proxy = { enable: false };\n"
    assert find_missing(build_base, build_bad) == ["export const proxy = { enable: true };"], \
        "self-test B63e：build/ 檔動基線行無 `原行:` 須攔（rev5:B-063 反例②）"

    # ── 新檔兩道（002 刀 U0 fix 輪補；`docs/ops/reference-src/code-gate-contracts.md` §4「新增型缺圈界標記（本刀兩新檔）」、
    #    spec FR-025／US6、brainstorm Q5「本刀能守＝兩新檔檔頭標記＋路徑落在所稱軌道範圍內」）：
    #    ①檔頭圈界標記 ②軌道×路徑相符。★rev5 形對「基線沒有的整檔」整檔豁免＝兩腿對 002 刀唯一的
    #    fork-delta 面（該刀 U3 兩支 base-web 新檔：T025 typings／T031 service wrapper；U4 之 T035
    #    續補 T031 該檔、不增新檔支數——對基線恆為我方新檔、兩道判定照跑）覆蓋率 0；下列各案即該退化形的測紅面。
    nf_bare = "declare namespace Api {\n  type S = { a: string };\n}\n"
    nf_head = ("// [rev6-inline BASE-WEB-ADAPT+ 002-system-settings] 系統設定 wire 型別新檔\n"
               + nf_bare)
    nf_buried = nf_bare + "// [rev6-inline BASE-WEB-ADAPT+ 002-system-settings] 埋在檔尾\n"
    assert find_new_file_marker(nf_bare) is None, "self-test NF1：無檔頭標記之新檔須攔"
    assert (find_new_file_marker(nf_head) or "").startswith("// [rev6-inline"), \
        "self-test NF2：檔頭標記須被認得（否則新檔面恆紅、腿無法使用）"
    assert find_new_file_marker(nf_buried) is None, \
        "self-test NF3：標記埋在首個實質碼行之後不算檔頭一行（憲法 §III「新檔僅檔頭一行標記」）"
    assert find_new_file_marker(
        "\n# [rev6-inline BASE-WEB-ADAPT+ 002-system-settings] 新 .env\nVITE_X=1\n") is not None, \
        "self-test NF4：`.env*` 的 `#` 前綴檔頭標記須被認得（`#` 臂非 vacuous 證）"
    assert find_new_file_marker("#tag = 'x [rev6-inline] y';\nconst a = 1;\n") is None, \
        "self-test NF5：`#` 起首之字串常值不得自證檔頭標記（B63g 之 FN2 反例、新檔面）"
    s1_real = {"BASE-WEB-ADAPT", "BASE-WEB-WRAPPER", "RUSTAPI-SOURCE-ISOLATION"}
    mk = "// [rev6-inline {}+ 002-system-settings] r"
    assert new_file_track_issue("src/typings/api/rev6-settings.d.ts",
                                mk.format("BASE-WEB-ADAPT"), s1_real) is None, \
        "self-test NF6：ADAPT 新檔落 `src/typings/api/` 須過（憲法 §III.1 範圍欄）"
    assert new_file_track_issue("src/service/api/rev6-settings.ts",
                                mk.format("BASE-WEB-WRAPPER"), s1_real) is None, \
        "self-test NF7：WRAPPER 新檔落 `src/service/api/rev6-*.ts` 須過"
    assert "不在其範圍欄新增面" in (new_file_track_issue(
        "src/service/api/rev6-settings.ts", mk.format("BASE-WEB-ADAPT"), s1_real) or ""), \
        "self-test NF8：軌道與檔路徑不符須攔（ADAPT 標記落 service wrapper 面）"
    assert new_file_track_issue("src/service/api/other.ts",
                                mk.format("BASE-WEB-WRAPPER"), s1_real) is not None, \
        "self-test NF9：WRAPPER 之 `rev6-` 前綴收窄須非 vacuous（缺前綴的新檔須攔）"
    assert new_file_track_issue("src/x.ts", mk.format("RUSTAPI-SOURCE-ISOLATION"),
                                s1_real) is not None, \
        "self-test NF10：RUSTAPI-SOURCE-ISOLATION 於 base-web 掃描面一律無授權"
    assert new_file_track_issue("src/x.ts", mk.format("SOME-STAR-TRACK"), s1_real) is None, \
        ("self-test NF11：§III.1 外之名不做名冊斷言——§III.2 表外宣告 3 與 rev5:ADR 0021 款 1 明寫"
         "「純新增檔不觸 ★軌道、§III.1 三軌道表非新增面之窮舉排除」，於此報紅即與憲法字面相衝")
    assert "失準" in (new_file_track_issue("src/x.ts", mk.format("A-FOURTH"),
                                           s1_real | {"A-FOURTH"}) or ""), \
        "self-test NF12：§III.1 在冊卻無新增面判準須 fail-loud（憲法表被改名／增列之偵測）"
    assert new_file_track_issue("src/x.ts", "// [rev6-inline] 無軌道名", s1_real) is not None, \
        "self-test NF13：檔頭標記抽不出軌道名須攔（形制不符）"
    # ── `+` 尾綴定形（002 刀 U3 補；`docs/ops/reference-src/code-gate-contracts.md` §4「`+` 尾綴＝新增型」）：新檔檔頭標記須為
    #    `[rev6-inline <軌道名>+ <刀名>]`——軌道名後緊接 `+`、缺即形制不符、紅指名；名冊外之名同受形制約束
    #    （§III.2 表外宣告 3 的新增型形本就是 `NAME+`）。一正一反、`.env*` 之 `#` 臂同釘。
    assert new_file_track_issue("src/typings/api/rev6-settings.d.ts",
                                "// [rev6-inline BASE-WEB-ADAPT+ 002-system-settings] r", s1_real) is None \
        and new_file_track_issue(".env.test", "# [rev6-inline BASE-WEB-ADAPT+ 002-system-settings] r",
                                 s1_real) is None, \
        "self-test NF17：帶 `+` 尾綴之新檔檔頭標記須過（`//` 與 `#` 兩臂）"
    for noplus in ("// [rev6-inline BASE-WEB-ADAPT 002-system-settings] r",       # .env 修改型裸形
                   "// [rev6-inline BASE-WEB-ADAPT(a) 002-system-settings] r",    # ★軌道修改型用途形
                   "// [rev6-inline SOME-STAR-TRACK 002-system-settings] r"):     # 名冊外之名、仍缺 `+`
        assert "`+` 尾綴" in (new_file_track_issue("src/typings/api/rev6-settings.d.ts", noplus, s1_real) or ""), \
            f"self-test NF18：新檔檔頭標記缺 `+` 尾綴須攔並指名形制（{noplus}）"

    # ── rev5:B-063 掃描面自證：暫存 git fixture 走**真** changed_files（pathspec＋濾網零打樁）——
    #    變異「pathspec 縮回 -- src/」或「濾網丟 .env」即在此測紅；根層限定與副檔名濾網一併釘住。
    #    ★巢狀 .env 反例分兩面、各釘一支（rev5 fix 輪補）：`sub/.env` 驗 pathspec 面（`.env*` 從
    #    repo 根逐字比、不以 .env 起首即不進 diff 輸出）；`.envs/.env` 驗濾網面（pathspec `*`
    #    會跨 `/` 而命中、唯 `_in_scan_scope` 根層限定擋得住——缺它則根層限定臂 vacuous、
    #    整個拔掉仍全綠，變異實測過）。
    tmp = tempfile.mkdtemp(prefix="fdlt-scanface-")
    try:
        def g(*args):
            # sh() 只清 GIT_* env、不隔離 ~/.gitconfig——全域 core.excludesFile 含 .env 會讓
            # add -A 漏收 fixture、commit.gpgsign=true 會讓 fixture commit 直接失敗，兩者都被
            # main() 誤診成「lint 邏輯壞」；故逐鍵以 -c 壓掉（rev5 實證過的兩條故障鏈）。
            r = sh(["git", "-c", "core.hooksPath=.git/no-hooks", "-c", "core.excludesFile=",
                    "-c", "commit.gpgsign=false", *args], tmp)
            assert r.returncode == 0, \
                f"self-test B63f：fixture git {' '.join(args)} 失敗：{r.stderr.strip()}"
        fixture = {
            "src/a.ts": "const a = 1;\n", "src/c.vue": "<template>x</template>\n",
            "src/style.css": ".a { color: red; }\n", "build/config/proxy.ts": "export const p = 1;\n",
            "build/notes.md": "note\n", ".env": "VITE_X=1\n", ".env.test": "VITE_Y=1\n",
            "sub/.env": "NESTED=1\n", ".envs/.env": "NESTED2=1\n", "package.json": "{}\n",
        }
        g("init", "-q")
        for rel, content in fixture.items():
            os.makedirs(os.path.dirname(os.path.join(tmp, rel)) or tmp, exist_ok=True)
            open(os.path.join(tmp, rel), "w", encoding="utf-8").write(content)
        g("add", "-A")
        g("-c", "user.name=fdlt", "-c", "user.email=fdlt@local", "commit", "-qm", "base")
        for rel in fixture:  # 全數改動——該進掃描面的與不該進的都動，濾網才受檢
            open(os.path.join(tmp, rel), "a", encoding="utf-8").write("changed\n")
        got = set(changed_files(tmp, "HEAD"))
        want = {"src/a.ts", "src/c.vue", "build/config/proxy.ts", ".env", ".env.test"}
        assert got == want, \
            f"self-test B63f：掃描面應恰為 src(.ts/.vue)＋build(.ts)＋根層 .env*（實得 {sorted(got)}）"
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    # ── 新檔兩道之**接線**自證（002 刀 U0 fix 輪）：NF1～NF13 只驗函式本體，接線壞掉（rev5 形之
    #    「新檔整檔 continue」）內容級斷言全綠也看不見——本案以暫存 git fixture 走**真** scan()
    #    （repo/baseline 參數化、零打樁），把新檔分支改回整檔 continue 即在此測紅。
    ntmp = tempfile.mkdtemp(prefix="fdlt-newfile-")
    try:
        def ng(*args):
            r = sh(["git", "-c", "core.hooksPath=.git/no-hooks", "-c", "core.excludesFile=",
                    "-c", "commit.gpgsign=false", *args], ntmp)
            assert r.returncode == 0, \
                f"self-test NF14：fixture git {' '.join(args)} 失敗：{r.stderr.strip()}"

        def nw(rel, content):
            os.makedirs(os.path.dirname(os.path.join(ntmp, rel)) or ntmp, exist_ok=True)
            open(os.path.join(ntmp, rel), "w", encoding="utf-8").write(content)

        ng("init", "-q")
        nw("src/a.ts", "const a = 1;\n")
        ng("add", "-A")
        ng("-c", "user.name=fdlt", "-c", "user.email=fdlt@local", "commit", "-qm", "base")
        nw("src/typings/api/rev6-bare.d.ts", nf_bare)            # 無檔頭標記 → 須進 unmarked
        nw("src/typings/api/rev6-ok.d.ts", nf_head)              # 檔頭標記＋路徑相符 → 須全綠
        nw("src/service/api/rev6-bad.ts",                        # 標記自稱 ADAPT、落 wrapper 面 → 須進 rogue
           mk.format("BASE-WEB-ADAPT") + "\nexport const q = 1;\n")
        nw("src/typings/components.d.ts",                        # 生成檔 → 豁免（放寬面的非 vacuous 證）
           "// Generated by unplugin-vue-components\nexport {};\n")
        ng("add", "-A")
        _ne, nu, nr, _nc, nst = scan(s1_real, {}, ntmp, "HEAD")
        assert [r for r, _a in nu] == ["src/typings/api/rev6-bare.d.ts"], \
            (f"self-test NF14：新檔缺檔頭圈界標記須被 scan 攔、且帶標記與生成檔不得誤報"
             f"（實得 {nu}）——新檔分支若整檔 continue，本案即恆綠")
        assert [r for r, _l, _w in nr] == ["src/service/api/rev6-bad.ts"] \
            and "不在其範圍欄新增面" in nr[0][2], \
            f"self-test NF15：新檔軌道×路徑不符須被 scan 攔並指名錯因（實得 {nr}）"
        assert nst == {"files": 4, "new_files": 4, "new_checked": 2}, \
            f"self-test NF16：新檔統計須為 4 檔／2 支過兩道（生成檔與缺標記者不計）（實得 {nst}）"
    finally:
        shutil.rmtree(ntmp, ignore_errors=True)

    # ── load_roster 守門自證（rev5 fix 輪第 2 輪先釘五守、確認輪補齊 RG9～RG15；rev6 R10 改形：
    #    RG14 由「≥4 樓地板」改為「零列＋無哨兵句＝紅」，另加 RG16～RG18 三案把空表哨兵句一正一反與
    #    樓地板移除的正向面釘住；fix 輪第 1 輪再加 RG20～RG23＝§III.1 範圍欄字面對賬一正三反、
    #    第 3 輪加 RG24＝純次序對調須綠）。合成憲法片段走**真** load_roster（path 參數化、同 B63f 之
    #    changed_files 範式）；die 走 sys.exit(2)、以 SystemExit 承接並驗 stderr 錯因關鍵詞（錯因驗對支、
    #    防「die 了但不是那道守」的假殺）。──────
    hdr = (
        "### III.1 預設可動軌道\n\n"
        "| 軌道 | 範圍 | 紀律 |\n|---|---|---|\n"
        "| **A-ONE** | `x` | y |\n| **A-TWO** | `x` | y |\n| **A-THREE** | `x` | y |\n\n"
        "### III.2 ★ 需 constitution 顯式授權軌道\n\n"
        "| 軌道 | 用途 | 範圍（檔案） | 紀律 |\n|---|---|---|---|\n"
    )
    rows_ok = (
        "| **★B-X** | (a) p | `src/a.ts`（1 處，修改型） | d |\n"
        "| **★B-X** | (b) p | `src/m/{b,c}.ts` | d |\n"
        "| **★B-Y** | (i) p | `src/d.ts`／`src/e.vue` | d |\n"
        "| ** ★B-Z** | (i) p | `src/f.ts` | d |\n"
    )
    rtmp = tempfile.mkdtemp(prefix="fdlt-roster-")
    try:
        def roster(body, header=hdr):
            p = os.path.join(rtmp, "c.md")
            open(p, "w", encoding="utf-8").write(header + body)
            return load_roster(p)

        def roster_die(tag, body, want, header=hdr, unwanted=()):
            # unwanted＝錯因**不得**出現的字面（002 刀 U0 fix 輪第 1 輪增）：只驗「有出現關鍵詞」
            # 會被「把全部軌道一起 dump」的籠統訊息滿足＝指名性被無聲放寬仍全綠。
            err = io.StringIO()
            try:
                with contextlib.redirect_stderr(err):
                    roster(body, header)
            except SystemExit:
                assert want in err.getvalue(), \
                    f"self-test {tag}：die 錯因不含「{want}」（實得 {err.getvalue()!r}）"
                for u in unwanted:
                    assert u not in err.getvalue(), \
                        (f"self-test {tag}：die 錯因不應含未漂移軌道「{u}」——籠統列出全部軌道＝"
                         f"讀者無從辨識何者漂移（實得 {err.getvalue()!r}）")
                return
            raise AssertionError(f"self-test {tag}：壞名冊形（{want}）未 die——該守被移除即此恆綠形")

        s1t, s2t = roster(rows_ok)
        assert s1t == {"A-ONE", "A-TWO", "A-THREE"} and set(s2t) == {"B-X", "B-Y", "B-Z"} \
            and s2t["B-X"]["b"] == {"src/m/b.ts", "src/m/c.ts"} \
            and s2t["B-Z"]["i"] == {"src/f.ts"}, \
            (f"self-test RG1：合成名冊載入失準——`** ★NAME**` 裝飾剝除（strip 集含空白）／"
             f"brace 展開／`／` 分隔任一壞掉（實得 s1={sorted(s1t)}／s2={s2t}）")
        roster_die("RG2", rows_ok + "| | (c) p | `src/z.ts` | d |\n", "續列")
        roster_die("RG3", "| **★B-X** | 無括號 | `src/a.ts` | d |\n" + rows_ok, "用途欄抽不出")
        roster_die("RG4", "| **★B-X** | (a) p | 無反引號路徑 | d |\n" + rows_ok, "範圍欄抽不出")
        roster_die("RG5", "| **★B-X** | (a) p | `src/{a,b}/{c,d}.ts` | d |\n" + rows_ok, "殘留 brace")
        roster_die("RG6", "| **★B-X** | (a) p | `src/a.ts（1 處）` | d |\n" + rows_ok, "殘留 brace")
        # RG7（rev5 fix 輪第 3 輪）：全表縮排一格（markdown 允許前置 ≤3 空格）須載入為與未縮排
        #   **完全相同**的名冊——舊形整列走 skip＝靜默漏收該用途，合法標記被誤報「用途不在集」
        #   並指向不必要的 Amendment（與 RG2 續列守同病之旁路；§III.1 與 §III.2 兩面一起釘）。
        pi = os.path.join(rtmp, "c-ind.md")
        open(pi, "w", encoding="utf-8").write("\n".join(
            " " + l if l.startswith("|") else l
            for l in (hdr + rows_ok).splitlines()) + "\n")
        assert load_roster(pi) == (s1t, s2t), \
            "self-test RG7：縮排表列須載入為與未縮排完全相同的名冊（縮排一格即該列靜默蒸發）"
        # RG8（rev5 fix 輪第 3 輪＋確認輪校準）：（…）注記**外**的非路徑反引號 token 須 die、
        #   不得靜默進檔案集——檔級硬邊界（§III.2 表外宣告 1）不因憲法措辭風格而放寬。
        #   （注記**內**的 token 改由排除處理＝RG9、不再走 die。）
        roster_die("RG8",
                   "| **★B-X** | (a) p | `src/a.ts` 見 `translateBackendMsg` | d |\n"
                   + rows_ok, "非路徑")
        # RG9（rev5 確認輪）：（…）注記內的反引號 token——含否定語境的路徑形——一律不入檔案集
        #   （rev5 實測：舊形「（不含 `src/theme/x.ts`）」的 x.ts 直接進授權集＝檔級硬邊界
        #   被注記靜默放寬）。
        _s1n, s2n = roster(
            "| **★B-X** | (a) p | `src/a.ts`（1 處，修改型）（不含 `src/theme/x.ts`） | d |\n"
            + rows_ok[rows_ok.index("| **★B-X** | (b)"):])
        assert s2n["B-X"]["a"] == {"src/a.ts"}, \
            f"self-test RG9：（…）注記內的路徑形 token 不得入集（實得 {sorted(s2n['B-X']['a'])}）"
        # RG10（rev5 確認輪）：缺行首 `|` 的表列（GFM 合法省略形）須 die、不得靜默蒸發——skip 家族第三形。
        roster_die("RG10", rows_ok + "**★B-W** | (a) p | `src/w.ts` | d |\n", "缺行首")
        # RG11（rev5 確認輪）：brace 逗號後裝飾空白（`{b, c}`）須載入為與 `{b,c}` 完全相同的
        #   名冊（舊形拼出 `src/m/ b.ts`＝合法授權檔靜默失真、誤導性紅指向不必要 Amendment）。
        assert roster(rows_ok.replace("{b,c}", "{b, c}")) == (s1t, s2t), \
            "self-test RG11：brace 內裝飾空白須 strip（{b, c} 應與 {b,c} 載入同名冊）"
        # RG12／RG13／RG15（rev5 確認輪）：三道舊守上釘——先前零測試、逐支變異全綠＝守被無聲移除
        #   不會有任何東西紅（表外宣告 2 反例守尤重：失效＝未開軌道名混進名冊、靜默放寬）。
        roster_die("RG12", "| **★MODAL-WIRING** | (a) p | `src/a.ts` | d |\n" + rows_ok,
                   "被掃進名冊")
        roster_die("RG13", rows_ok, "須恰 3",
                   header=hdr.replace("| **A-THREE** | `x` | y |\n", ""))
        # RG14（rev6 R10 改形、取代 rev5「須 ≥4」案）：§III.2 零列且無哨兵句＝die 指名「哨兵」
        #   ——rev5 樓地板守「名冊被無聲移除」的目的由哨兵句承擔；此案＝該守被移除即恆綠形。
        roster_die("RG14", "", "哨兵")
        roster_die("RG15", "", "名冊掃描為空", header=(
            "### III.1 預設可動軌道\n\n### III.2 ★ 需 constitution 顯式授權軌道\n\n"))
        # RG16（rev6 R10 正向）：零列＋哨兵句（憲法字面、strip 後全等）＝綠、載入回 s1 三名、s2 空。
        s1e, s2e = roster("\n" + SENTINEL + "\n\n**表外三項適用宣告**：\n1. 範圍欄的處數為估值。\n")
        assert s1e == {"A-ONE", "A-TWO", "A-THREE"} and s2e == {}, \
            f"self-test RG16：零列＋哨兵句須載入為 s1 三名、s2 空（實得 s1={sorted(s1e)}／s2={s2e}）"
        # RG17（rev6 R10 矛盾守）：哨兵句與資料列並存＝die 指名「並存」（首列落入時哨兵句須同批移除）。
        roster_die("RG17", rows_ok + "\n" + SENTINEL + "\n", "並存")
        # RG18（rev6 樓地板移除的正向證）：★段 2 列、無哨兵句＝合法（≥1 列即可；rev5 形對此 die「須 ≥4」）。
        _s1two, s2two = roster(rows_ok[rows_ok.index("| **★B-Y**"):])
        assert set(s2two) == {"B-Y", "B-Z"}, \
            f"self-test RG18：★段 2 列無哨兵句須載入為 s2 兩名（rev5 ≥4 樓地板已移除；實得 {sorted(s2two)}）"
        # RG19：哨兵句字面被改（少一字）＝不算哨兵、零列即 die——strip 後全等判準之非 vacuous 證。
        roster_die("RG19", "\n" + SENTINEL.replace("首列", "") + "\n", "哨兵")
        # ── RG20～RG23（002 刀 U0 fix 輪第 1 輪補）：§III.1 範圍欄字面對賬（load_roster 斷言⑥）。
        #    化名表（hdr 之 A-ONE／A-TWO／A-THREE）射程外，故此四案改用**憲法實名三列**的合成表頭；
        #    缺此對賬則 Amendment 收窄範圍欄後 S1_NEW_FILE_FACE 的 lambda 仍放行舊面而全鏈照綠
        #    （放寬方向靜默失準）——RG21～RG23 即該守被移除時的恆綠形。
        hdr_real = (
            "### III.1 預設可動軌道\n\n"
            "| 軌道 | 範圍 | 紀律 |\n|---|---|---|\n"
            "| **BASE-WEB-ADAPT** | `.env*`＋`src/typings/api/` 新檔 | y |\n"
            "| **BASE-WEB-WRAPPER** | `src/service/api/rev6-*.ts` 新檔 | y |\n"
            "| **RUSTAPI-SOURCE-ISOLATION** | rust-api 整棵樹 | y |\n\n"
            "### III.2 ★ 需 constitution 顯式授權軌道\n\n"
            "| 軌道 | 用途 | 範圍（檔案） | 紀律 |\n|---|---|---|---|\n"
        )
        s1r, _s2r = roster(rows_ok, header=hdr_real)
        assert s1r == set(S1_RANGE_LITERAL), \
            f"self-test RG20：憲法 §III.1 實名三列逐字須綠（實得 s1={sorted(s1r)}）"
        # RG21：WRAPPER 範圍欄由 `rev6-*.ts` 收窄為 `rev6-settings.ts`——名字集不變、s1_rows 仍 3、
        #   缺鍵 fail-loud 不觸發，唯本對賬攔得住（finding 所述之 over-permit 失效鏈）。
        roster_die("RG21", rows_ok, "範圍欄字面", header=hdr_real.replace(
            "`src/service/api/rev6-*.ts` 新檔", "`src/service/api/rev6-settings.ts` 新檔"))
        # RG22：ADAPT 範圍欄的 typings 目錄被改——die 須**只**指名漂移的那一條（未漂移的另兩名
        #   不得出現：籠統 dump 全表＝讀者無從辨識何者漂移）。
        roster_die("RG22", rows_ok, "BASE-WEB-ADAPT", header=hdr_real.replace(
            "`src/typings/api/` 新檔", "`src/typings/` 新檔"),
            unwanted=("BASE-WEB-WRAPPER", "RUSTAPI-SOURCE-ISOLATION"))
        # RG23：實名列被改名（少收一鍵）——got 缺該鍵亦不等，同一道守即時攔下（原僅由
        #   new_file_track_issue 於「有新檔自稱該名」時才 fail-late）。
        roster_die("RG23", rows_ok, "BASE-WEB-WRAPPER", header=hdr_real.replace(
            "**BASE-WEB-WRAPPER**", "**BASE-WEB-WRAPPER-X**"),
            unwanted=("BASE-WEB-ADAPT", "RUSTAPI-SOURCE-ISOLATION"))
        # RG24（fix 輪第 3 輪補）：ADAPT 範圍欄兩 token **純前後對調**＝語意等價（下游只做成員判定、
        #   欄內先後無語意）須**綠**。序敏感比對（tuple）會把這種純排版 Amendment 判成 rc 2、且訊息
        #   指向「S1_NEW_FILE_FACE 須同批重導」的錯修法——把本對賬改回 tuple 比較即本案紅。
        s1swap, _s2swap = roster(rows_ok, header=hdr_real.replace(
            "`.env*`＋`src/typings/api/` 新檔", "`src/typings/api/` 新檔＋`.env*`"))
        assert s1swap == set(S1_RANGE_LITERAL), \
            f"self-test RG24：範圍欄純對調須綠（次序不計；實得 s1={sorted(s1swap)}）"
    finally:
        shutil.rmtree(rtmp, ignore_errors=True)

    # ── CLI 引數解析（rev6 加 `test`／`--constitution`）：三形＋兩用法錯釘住。
    assert _parse_args([]) == (False, CONSTITUTION), "self-test CLI1：無引數＝全掃＋預設憲法"
    assert _parse_args(["test"]) == (True, CONSTITUTION), "self-test CLI2：`test`＝只跑 self-test"
    assert _parse_args(["--constitution", "/x/c.md"]) == (False, "/x/c.md") \
        and _parse_args(["--constitution=/x/c.md"]) == (False, "/x/c.md"), \
        "self-test CLI3：`--constitution <path>` 兩形皆須收"
    assert _parse_args(["bogus"]) is None and _parse_args(["--constitution"]) is None, \
        "self-test CLI4：未知引數／缺路徑值須回 None（rc 64）"


def assert_baseline():
    """掃描面可達性斷言之一（rev6 取代 rev5「修改型 ≥1 處」的列數斷言）：源倉在場且切在 example。
    源倉缺席＝die rc 2（bootstrap 已斷言在場、正常不觸；唯讀捷徑模式 `git submodule update --init`
    無源倉＝無基線、CLAUDE.md §3 明寫不可做 base-web 開發）。"""
    if not os.path.isdir(FORK):
        die(f"最原始源-基線目錄不存在：{FORK}（bootstrap 建源倉後自動恢復實跑；bash tools/bootstrap.sh）")
    r = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], FORK)
    if r.returncode != 0:
        die(f"基線 repo 不可讀：{FORK}")
    cur = r.stdout.strip()
    if cur != BASELINE:
        die(f"最原始源-基線未就位：{FORK} 現在 '{cur}'、須切到 '{BASELINE}'"
            f"（git -C {FORK} checkout {BASELINE}）")


def _in_scan_scope(f):
    """rev5:B-063 收案規則：src/ 之 .ts/.vue＋build/ 之 .ts＋**根層** `.env` 族。
    `.env*` 無副檔名、獨立收案（根層限定、以 .env 起首），不硬塞 endswith 濾網。"""
    if f.startswith("src/"):
        return f.endswith((".ts", ".vue"))
    if f.startswith("build/"):
        return f.endswith(".ts")
    return "/" not in f and f.startswith(".env")


def changed_files(repo=BASEWEB, baseline=BASELINE):
    """掃描面（rev5:B-063 擴）：rev4 舊面只 `-- src/` ⇒ `.env*` 與 `build/` 的 fork-delta 全靠人工
    review、upstream rebase 解錯不會紅。repo/baseline 參數化＝讓 self-test 能以暫存 git
    fixture 走**同一條**真掃描鏈（pathspec＋濾網零打樁），變異「縮回 src/」即測紅。
    ★git diff 非零即 die＝掃描面可達性斷言之二（零差異與「diff 跑不動」是兩件事、絕不同回空集）。"""
    r = sh(["git", "diff", "--name-only", baseline, "--", "src/", "build/", ".env*"], repo)
    if r.returncode != 0:
        die(f"無法 diff base-web vs {baseline}：{r.stderr.strip()}")
    return [f for f in r.stdout.splitlines() if _in_scan_scope(f)]


def scan(s1, s2, repo=BASEWEB, baseline=BASELINE):
    """回 (errs, unmarked, rogue, checked_total, stats)；stats＝{"files": 掃描面檔數,
    "new_files": 我方新檔數, "new_checked": 過新檔兩道判定之檔數}（供修改型 0 處時印出掃描面實況、
    證 vacuous 是合法的而非掃描面壞掉）。repo/baseline 參數化（同 [`changed_files`] 之 B63f 範式）
    ＝讓 self-test 以暫存 git fixture 走**同一條**真掃描鏈驗新檔兩腿的**接線**——腿寫好卻沒接上
    （rev5 形之整檔 continue）正是 002 刀 U0 fix 輪所修的病，內容級斷言看不見。"""
    errs, unmarked, rogue = [], [], []
    checked_total, new_files, new_checked = 0, 0, 0
    rels = list(changed_files(repo, baseline))
    # ── 基線原文並行預取（rev5:B-130／rev5:ADR 0061）────────────────────────────────────
    # 本函式的成本 **99% 在 subprocess 等待**、不在判定邏輯（rev5 2026-08-25 cProfile：
    # select.poll 14.338s／14.260s 總時，檔案 I/O 僅 0.167s）——每個 changed file 各起一次
    # `git show` 取基線原文，逐次序列等待。drvfs（9p）下單次約 0.29s，數十檔即十數秒。
    # ★預取只把「等待」重疊，判定邏輯與逐檔順序一字不動（下方迴圈照原序消費），
    #   故結果逐位元組相同——git show 為唯讀、對同一 BASELINE 冪等，並行無序副作用。
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as ex:
        bases = dict(zip(rels, ex.map(
            lambda r: sh(["git", "show", f"{baseline}:{r}"], repo), rels)))
    for rel in rels:
        base = bases[rel]
        ours_path = os.path.join(repo, rel)
        if base.returncode != 0:
            # ★我方新檔（基線沒有此檔）：rev5 形整檔豁免＝圈界腿與授權判定對新檔全 vacuous
            #   （002 刀 U0 fix 輪補；該刀 fork-delta 面恰為兩支新檔）。改走新檔兩道——
            #   ①檔頭圈界標記 ②標記自稱 §III.1 軌道時檔路徑須落其範圍欄新增面。
            new_files += 1
            try:
                ours = open(ours_path, encoding="utf-8").read()
            except FileNotFoundError:
                continue                     # diff 列出但工作樹已無（刪除態）——無可判定面
            if is_generated(ours):
                continue                     # 生成檔（憲法 §III 生成檔紀律）→ 重算保證、豁免手標
            marker = find_new_file_marker(ours)
            if marker is None:
                unmarked.append((rel, _first_substantive(ours) or "（檔內無實質碼行）"))
                continue
            new_checked += 1
            why = new_file_track_issue(rel, marker, s1)
            if why:
                rogue.append((rel, marker, why))
            continue
        try:
            ours = open(ours_path, encoding="utf-8").read()
        except FileNotFoundError:
            continue
        if is_generated(ours):
            continue  # 生成檔（elegant-router 等）→ fork-delta 由重算保證、豁免手標
        for m in find_missing(base.stdout, ours):
            errs.append((rel, m))
        for a in find_unmarked_additions(base.stdout, ours):
            unmarked.append((rel, a))
        hits, checked = find_rogue_tracks(rel, ours, s1, s2)
        checked_total += checked
        for line, why in hits:
            rogue.append((rel, line, why))
    return errs, unmarked, rogue, checked_total, {"files": len(rels), "new_files": new_files,
                                                  "new_checked": new_checked}


def main(argv):
    parsed = _parse_args(argv[1:])
    if parsed is None:
        print(USAGE, file=sys.stderr)
        return 64
    test_only, constitution = parsed
    try:
        self_test()
    except AssertionError as e:
        die(f"self-test 失敗（lint 邏輯壞）：{e}")
    if test_only:
        print("[fork-delta-lint] ✓ self-test 過（修改型缺原行／新增型缺圈界／新檔檔頭標記（含 `+` 尾綴定形）＋軌道×路徑"
              "（含真 scan 接線 fixture）／五形抽取＋token 換世代／"
              "分層授權判定／範圍欄展開器／掃描面 fixture／名冊載入守 RG1～RG24 含空 ★表哨兵句一正一反"
              "與 §III.1 範圍欄字面對賬二正三反（含純對調須綠）／template 形行尾 `-->`／修改型樓地板守／CLI 引數）")
        return 0
    # 含結構斷言（空名冊／★段零列須哨兵句／§III.1 恰 3／表外宣告 2 反例／升維非空／§III.1 範圍欄字面對賬＝die）
    s1, s2 = load_roster(constitution)
    assert_baseline()
    tip = sh(["git", "rev-parse", "--short", BASELINE], BASEWEB).stdout.strip()
    errs, unmarked, rogue, checked_total, stats = scan(s1, s2)
    if errs or unmarked or rogue:
        if errs:
            print(f"[fork-delta-lint] ✗ {len(errs)} 條 example 上游 inline 行被改動卻缺 `原行:` 標記"
                  f"（constitution §III 修改型；基線 {BASELINE}@{tip}）：")
            for rel, m in errs:
                print(f"    {rel}｜缺 原行: {m}")
            print("  補法：緊鄰改動行之上加 `// [rev6-inline <track>] 原行: <上列原碼>`。")
        if unmarked:
            print(f"[fork-delta-lint] ✗ {len(unmarked)} 個新增碼區塊／新檔缺 rev6-inline 圈界標記"
                  f"（constitution §III 新增型圈界；基線 {BASELINE}@{tip}）：")
            for rel, a in unmarked:
                print(f"    {rel}｜未圈界新增首行: {a}")
            print("  補法：新增區塊上方加 `// [rev6-inline <track>+ <feature>] <說明>`；"
                  "大區塊用 START…END 圈界；**新檔**於檔頭一行（`.env*` 用 `#` 前綴形、"
                  "須在首個實質碼行之前）。生成檔（Generated by header）自動豁免。")
        if rogue:
            print(f"[fork-delta-lint] ✗ {len(rogue)} 個標記未過授權判定"
                  f"（修改型＝§III.2 ★軌道驗軌道×用途×檔案三元組＋§III.1 三軌道驗檔面收窄；"
                  f"新檔＝檔頭標記 `+` 尾綴定形＋自稱軌道之 §III.1 範圍欄新增面）：")
            for rel, line, why in rogue:
                print(f"    {rel}｜{why}｜{line}")
            print("  補法：修改型標記改用名冊內（軌道,用途）實名且只落授權檔，新用途／新軌道須先走"
                  " §V.2 Amendment 開立；新檔標記帶 `+` 尾綴、改用範圍欄涵蓋該路徑的軌道"
                  "（§III.1；純新增檔不觸 ★軌道＝rev5:ADR 0021 款 1）。")
        return 1
    floor = floor_violation(checked_total)
    if floor:
        die(f"{floor}——掃描面 {stats['files']} 檔（base-web vs {BASELINE}@{tip}：src/ .ts/.vue＋build/ .ts＋根層 .env*）")
    print(f"[fork-delta-lint] ✓ base-web 修改型全帶原行（{checked_total} 處授權判定皆合："
          f"★軌道三元組＋§III.1 檔面收窄）、新增型全圈界"
          f"（含我方新檔 {stats['new_checked']} 支：檔頭標記＋軌道×路徑皆合）"
          f"（self-test 過；基線 {BASELINE}@{tip}）")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
