#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""tools/route-artifact-gate.py — 路由外掛產物檔碼面閘（004 刀 U8；憲法 §III.2 `★BASE-WEB-MANAGE-PAGE-WIRING` (i) 列之產物檔紀律、
`docs/ops/reference-src/code-gate-contracts.md` §3②；承 rev5:tools/route-artifact-gate.py 新寫；名冊＝RUNBOOK §12 碼面閘表）

子命令：
  check [--constitution <path>]   （預設）三道斷言；`--constitution` 只供本閘自身的變異驗證、日常一律預設憲法路徑
  test                            離線 self-test（暫存樹＋subprocess 全樁；零 docker／node、毫秒級）

守什麼：`src/router/elegant/{imports,routes,transform}.ts`＋`src/typings/elegant-router.d.ts` 由路由外掛（`build/plugins/router.ts`）
  重算產出；憲法對它們採產物檔紀律（禁手改、不要求逐行標記），fork-delta 檢查亦以產物檔頭豁免之——本閘是這幾支唯一的機器守。
三道斷言：
  ①產出檔集對賬：空沙盒觀測到的外掛實產出集 ＝ base-web/src 下帶產物檔頭之檔集 ＝ 憲法該列範圍欄
    「（產物檔 N 支）」注記所轄路徑集（雙向差集即紅：漏列＝該支無授權亦無守、幽靈宣告＝授權射程虛胖且無機器守看管）。
    以注記分群而非整欄比：該列同列著非產物的 locale／app.d.ts。產出集現場觀測、不寫死清單。
  ②重算冪等（種＝工作樹現況）：新增／搬移 view 後忘了重算、或重算結果沒進版控，即不等。
  ③零手改（種＝上游基線 fork260509-soybean-admin-base）：外掛對 routes.ts 走增量合併（只補缺的 route、保留既有條目），
    以工作樹為種時手改行會存活、②照綠；以基線為種整份重算，手改無處可藏。基線恆在 `example` 由 fork-delta-lint 首步斷言承擔。
不變式：
  · 重算一律在 base-web 容器內 `/tmp` 沙盒；對 `/app` 只讀（symlink 視圖樹＋載入外掛設定）、比對在 host 做——pre-commit 並行 harness 各閘唯讀。
  · 外掛設定不重抄：runner 直接載入現行 `build/plugins/router.ts`。憲法列解析不重寫：授權集取 fork-delta-lint 之 `load_roster`、
    產物檔組取其同一支 `_expand_range_files` 展開注記轄區，兩者以 ⊆ 交叉對賬（兩解析漂移即 fail-loud）。
環境語意（ADR-00019）：docker 不在 PATH／compose 兩檔缺／base-web 容器未起＝具名跳過 rc 0；容器在而重算失敗、外掛零產出、
  憲法列或基線種子不完整＝rc 2；基線源倉缺席＝只③具名跳過並警告。
退出碼：0 綠或具名跳過／1 任一道不通過／2 環境或結構異常／64 用法錯。
接線：pre-commit route-artifact-gate 段（`base-web` pin bump、本檔或憲法 staged 時 `check`）、`for` 自測迴圈與 bootstrap 名冊（`test`）、
  README 樹、RUNBOOK §12 兩表。重算者＝dev server 內之該外掛與本閘沙盒；`pnpm gen-route` 是互動腳手架、不重算（rev5:L-053）。
"""
import contextlib
import difflib
import importlib.util
import io
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import tarfile
import tempfile
import time
import unittest
import unittest.mock
import warnings

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONSTITUTION_REL = os.path.join(".specify", "memory", "constitution.md")
BASE_WEB_REL = "base-web"
BASELINE_REL = "fork260509-soybean-admin-base"
ROSTER_TOOL = os.path.join(REPO_ROOT, "tools", "fork-delta-lint.py")
TRACK, PURPOSE = "BASE-WEB-MANAGE-PAGE-WIRING", "i"
GENERATED_HEADER = "Generated by elegant-router"   # 外掛自寫之檔頭字樣
HEADER_WINDOW = 8                                  # 限檔頭（同 fork-delta-lint is_generated 之窗）：散文提及不算產物檔
COMPOSE_FILES = ("docker-compose.yml", "docker-compose.dev.yml")
SERVICE = "base-web"
SANDBOX_PREFIX = "/tmp/route-artifact-gate."
START_HINT = "docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --wait"
TAG = "[route-artifact-gate]"
USAGE = "用法：tools/route-artifact-gate.py [check|test] [--constitution <path>]"
RE_REL = re.compile(r"^src/[A-Za-z0-9_./-]+$")
RE_NOTE = re.compile(r"（[^）]*）")                          # 範圍欄之（…）注記（分群錨；同 _expand_range_files 之 span 形）
RE_ARTIFACT_NOTE = re.compile(r"（產物檔[^）]*?(\d+)\s*支[^）]*）")   # 產物檔那一群的注記＋其自稱支數
DIFF_HEAD = 40
# 兩道重算斷言：(沙盒名, 種子根相對 repo 根, 不通過時之標題, 去處)
SEEDED = (
    ("worktree", BASE_WEB_REL, "② 重算不冪等（種＝工作樹現況）",
     "view 樹變了而產物沒跟上——讓 dev server 內之外掛重算（新 view 落地即自動重算；未觸發則重啟 base-web 服務）後連同產物一起 commit"),
    ("baseline", BASELINE_REL, "③ 產物檔遭手改（種＝上游基線）",
     "產物檔禁手改（憲法 §III.2 該列）——還原手改、需要的變更改 view 樹或外掛設定後重算"),
)

# 沙盒 runner（容器內 node；cwd＝沙盒＝外掛輸出根）。產出是外掛建構子的副作用、未曝出可 await 的 promise，
# 故輪詢到「src 下真檔皆於本輪寫過（mtime ≥ t0）且連續 QUIET 次快照不變」；symlink（視圖樹）不下探。
NODE_RUNNER = r"""
import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const POLL_MS = 250, QUIET = 4, DEADLINE_MS = 60000;
function walk(dir, base, out) {
  for (const name of fs.readdirSync(dir).sort()) {
    const abs = path.join(dir, name), rel = `${base}/${name}`, st = fs.lstatSync(abs);
    if (st.isSymbolicLink()) continue;
    if (st.isDirectory()) walk(abs, rel, out);
    else if (st.isFile()) out[rel] = `${st.size}:${st.mtimeMs}`;
  }
}
const t0 = Date.now();
const mod = await import('/app/build/plugins/router.ts');
mod.setupElegantRouter();
let prev = null, quiet = 0;
while (Date.now() - t0 < DEADLINE_MS) {
  await new Promise(r => setTimeout(r, POLL_MS));
  const cur = {};
  walk(path.join(root, 'src'), 'src', cur);
  const names = Object.keys(cur), json = JSON.stringify(cur);
  const fresh = names.length > 0 && names.every(n => Number(cur[n].split(':')[1]) >= t0);
  quiet = fresh && json === prev ? quiet + 1 : 0;
  prev = json;
  if (quiet >= QUIET) {
    console.log('__FILES__' + JSON.stringify(names));
    process.exit(0);
  }
}
console.error('[runner] 外掛產出未在期限內靜止；沙盒狀態：' + prev);
process.exit(3);
"""

# 容器內兩段 sh（`$1`＝沙盒根；一律位置參數、不做字串內插）。寫面只在沙盒根之下；`/app` 只出現在 symlink 來源。
_BOX_GUARD = 'box=$1; case "$box" in ' + SANDBOX_PREFIX + '*) ;; *) echo "沙盒根不合前綴" >&2; exit 64 ;; esac\n'
# 觀測：空沙盒跑一次外掛、stdout 末行回報實產出集；stdin＝runner 原文（落沙盒根、供下一段重用）。失敗即清沙盒。
OBSERVE_SH = ("set -e\n" + _BOX_GUARD +
              'trap \'rc=$?; [ "$rc" -eq 0 ] || rm -rf "$box"\' EXIT\n'
              'rm -rf "$box"; mkdir -p "$box/observe/src"\n'
              'ln -s /app/src/views "$box/observe/src/views"\n'
              'cat >"$box/runner.mjs"\n'
              'cd "$box/observe" && node ../runner.mjs\n')
# 重算：stdin＝種子 tar（`<沙盒名>/<相對路徑>`）；`$2…`＝沙盒名；各沙盒並行跑外掛，stdout＝各沙盒 src 下真檔之 tar。收場必清沙盒。
REGEN_SH = ("set -e\n" + _BOX_GUARD +
            'trap \'rm -rf "$box"\' EXIT\n'
            'shift; cd "$box"; tar -xf -\n'
            'for s in "$@"; do mkdir -p "$s/src"; ln -s /app/src/views "$s/src/views"\n'
            '  ( cd "$s" && node ../runner.mjs >"../$s.log" 2>&1; echo $? >"../$s.rc" ) &\n'
            'done; wait\n'
            'for s in "$@"; do [ "$(cat "$s.rc")" = 0 ] || { echo "沙盒 $s 重算失敗：" >&2; cat "$s.log" >&2; exit 3; }; done\n'
            'find "$@" -type f >files.list; tar -cf - -T files.list\n')
CLEAN_SH = "set -e\n" + _BOX_GUARD + 'rm -rf "$box"\n'


class GateError(Exception):
    """環境或結構異常（rc 2）：訊息即輸出行。"""


def _say(msg, err=False):
    print(msg, file=sys.stderr if err else sys.stdout, flush=True)


def compose_argv(*args):
    return ["docker", "compose", "-f", COMPOSE_FILES[0], "-f", COMPOSE_FILES[1], *args]


def _sh(argv, root, stdin=None):
    """外部呼叫單一咽喉（bytes 進出；self-test 一律樁掉 subprocess.run）。"""
    return subprocess.run(argv, cwd=root, input=stdin, capture_output=True)


def _text(raw):
    return (raw or b"").decode("utf-8", "replace").strip()


def docker_skip_reason(root):
    if shutil.which("docker") is None:
        return "docker 不在 PATH"
    missing = [n for n in COMPOSE_FILES if not os.path.isfile(os.path.join(root, n))]
    return "repo 根缺 " + "、".join(missing) if missing else None


def container_is_running(root):
    """`ps -q --status running base-web` 有輸出即在跑；ps 本身非零一律歸「未在跑」（補救同為起 stack）。"""
    return bool(_text(_sh(compose_argv("ps", "-q", "--status", "running", SERVICE), root).stdout))


def _range_cell(path):
    """憲法 §III.2 目標列之範圍欄原文。load_roster 只回展平後的路徑集、取不到注記分群，故在此再掃一次原文；
    掃描錨與剝飾同 load_roster，且所得再以 ⊆ 與其對賬（見 [`load_declared`]）＝兩解析漂移不靜默。"""
    want = f"({PURPOSE})"
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    for line in lines:
        cells = line.split("|")
        if len(cells) > 4 and cells[1].strip().strip("*★ ") == TRACK and cells[2].strip().startswith(want):
            return cells[3]
    raise GateError(f"憲法 §III.2 掃不到 ★{TRACK} {want} 列的範圍欄原文——列形被改動？")


def artifact_group(cell, expand):
    """範圍欄 → (產物檔組路徑集, 注記自稱支數)。該欄為「路徑群（注記）／路徑群（注記）…」形，
    唯注記能辨哪一群是產物檔；注記轄其前一段（自上一注記之後至本注記之前）。"""
    notes = [(m.start(), m.end()) for m in RE_NOTE.finditer(cell)]
    for idx, (a, b) in enumerate(notes):
        m = RE_ARTIFACT_NOTE.fullmatch(cell[a:b])
        if m:
            return frozenset(expand(cell[notes[idx - 1][1] if idx else 0:a])), int(m.group(1))
    raise GateError(f"憲法 §III.2 ★{TRACK} ({PURPOSE}) 列範圍欄找不到「（產物檔 N 支）」注記——"
                    "①的另一邊即該注記所轄路徑群；注記被改寫即無從辨識產物檔組，「比不出來」不算綠")


def load_declared(constitution_path):
    """憲法 §III.2 目標列 → (範圍欄全路徑集, 產物檔組路徑集, 該組自稱支數)。
    全路徑集＝授權面（解析＝fork-delta-lint `load_roster`，連同其全部結構斷言）；產物檔組＝①雙向對賬的另一邊。
    其結構斷言失敗（SystemExit）、目標列缺席、兩解析漂移皆 GateError。"""
    try:
        spec = importlib.util.spec_from_file_location("_route_artifact_gate_roster", ROSTER_TOOL)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        expand = mod._expand_range_files                       # noqa: SLF001 — 展開規則同源，重寫一份即與憲法措辭脫節
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", ResourceWarning)   # 載入器內部 open() 未關檔之噪音、非本閘訊號
            _s1, s2 = mod.load_roster(constitution_path)
    except SystemExit as ex:
        raise GateError(f"憲法名冊載入失敗（原因見上一行；載入器＝tools/fork-delta-lint.py 之 load_roster）：{constitution_path}") from ex
    except (OSError, ImportError, AttributeError) as ex:
        raise GateError(f"取不到名冊載入器 tools/fork-delta-lint.py 之 load_roster／_expand_range_files（{ex}）") from ex
    files = s2.get(TRACK, {}).get(PURPOSE)
    if not files:
        raise GateError(f"憲法 §III.2 找不到 ★{TRACK} ({PURPOSE}) 列——軌道被改名或撤銷？本閘的授權來源即該列")
    declared = frozenset(files)
    artifacts, claimed = artifact_group(_range_cell(constitution_path), expand)
    if not artifacts <= declared:
        raise GateError(f"產物檔組解析與 load_roster 授權集漂移：{sorted(artifacts - declared)} 在組內卻不在授權集"
                        "——兩支解析對同一列讀出不同結果，判準不可用")
    return declared, artifacts, claimed


def has_generated_header(path):
    with open(path, encoding="utf-8", errors="replace") as fh:
        return any(GENERATED_HEADER in line for _, line in zip(range(HEADER_WINDOW), fh))


def scan_generated(base_web_root):
    """`<base-web>/src/**` 帶產物檔頭之檔（相對 base-web 之 `/` 路徑、排序 tuple）。"""
    out = []
    for dirpath, _dirs, names in os.walk(os.path.join(base_web_root, "src")):
        out += [os.path.relpath(os.path.join(dirpath, n), base_web_root).replace(os.sep, "/")
                for n in names if has_generated_header(os.path.join(dirpath, n))]
    return tuple(sorted(out))


def roster_verdict(produced, header_set, artifacts):
    """①之判定核 → (產出集≠檔頭集: bool, 憲法漏列: list, 憲法幽靈宣告: list)。後兩項＝對產物檔組之**雙向**差集
    （憲法該列語句「本列產物檔集＝外掛實際產出檔集」）。生產面與 self-test 同呼本函式。"""
    produced, artifacts = set(produced), set(artifacts)
    return produced != set(header_set), sorted(produced - artifacts), sorted(artifacts - produced)


def pack_tar(files):
    """{名: bytes} → tar bytes（mtime 0＝早於 runner 之 t0，種子必被視為「本輪未寫」）。"""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tar:
        for name in sorted(files):
            info = tarfile.TarInfo(name)
            info.size = len(files[name])
            tar.addfile(info, io.BytesIO(files[name]))
    return buf.getvalue()


def unpack_tar(raw):
    """tar bytes → {名: bytes}（只取一般檔）。"""
    out = {}
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r:") as tar:
        for member in tar:
            if member.isfile():
                out[member.name] = tar.extractfile(member).read()
    return out


def compare_regenerated(regen, rels, worktree_root):
    """逐支比對「沙盒重算所得 bytes」與工作樹檔 → 不一致之 [(rel, 說明或 diff)]。生產面與 self-test 同呼本函式。"""
    bad = []
    for rel in rels:
        path = os.path.join(worktree_root, *rel.split("/"))
        new = regen.get(rel)
        if new is None:
            bad.append((rel, "沙盒重算未產出該檔"))
        elif not os.path.isfile(path):
            bad.append((rel, "工作樹缺該檔"))
        else:
            with open(path, "rb") as fh:
                old = fh.read()
            if old != new:
                diff = difflib.unified_diff(old.decode("utf-8", "replace").splitlines(), new.decode("utf-8", "replace").splitlines(),
                                            f"工作樹/{rel}", f"重算/{rel}", lineterm="")
                bad.append((rel, "\n".join(list(diff)[:DIFF_HEAD])))
    return bad


def observe(root, box):
    """空沙盒跑一次外掛 → 實產出集（相對沙盒根之 `src/…`、排序 tuple）。"""
    r = _sh(compose_argv("exec", "-T", SERVICE, "sh", "-c", OBSERVE_SH, "sh", box), root, stdin=NODE_RUNNER.encode("utf-8"))
    if r.returncode != 0:
        raise GateError(f"容器在跑而空沙盒觀測失敗（rc {r.returncode}）：{_text(r.stderr) or _text(r.stdout)}")
    for line in reversed(_text(r.stdout).splitlines()):
        if line.startswith("__FILES__"):
            try:
                return tuple(sorted(json.loads(line[len("__FILES__"):])))
            except ValueError as ex:
                raise GateError(f"沙盒 runner 回報之產出集非合法 JSON（{ex}）") from ex
    raise GateError(f"沙盒 runner 未回報產出集：{_text(r.stdout)}")


def regenerate(root, box, seeds):
    """seeds＝{沙盒名: {rel: bytes}} → {沙盒名: {rel: bytes}}（各沙盒重算後 src 下之真檔）。"""
    names = sorted(seeds)
    payload = pack_tar({f"{name}/{rel}": data for name in names for rel, data in seeds[name].items()})
    r = _sh(compose_argv("exec", "-T", SERVICE, "sh", "-c", REGEN_SH, "sh", box, *names), root, stdin=payload)
    if r.returncode != 0:
        raise GateError(f"容器在跑而沙盒重算失敗（rc {r.returncode}）：{_text(r.stderr)}")
    try:
        files = unpack_tar(r.stdout)
    except tarfile.TarError as ex:
        raise GateError(f"沙盒重算回傳非 tar（{ex}）") from ex
    out = {name: {} for name in names}
    for member, data in files.items():
        name, _, rel = member.partition("/")
        out.setdefault(name, {})[rel] = data
    return out


def _assertions(root, constitution_path):
    """三道斷言 → (problems, notes, 產出支數)。憲法列先於任何沙盒動作解析；沙盒於重算段收場自清、未走到重算即在此清。"""
    declared, artifacts, claimed = load_declared(constitution_path)
    worktree = os.path.join(root, BASE_WEB_REL)
    header_set = scan_generated(worktree)
    box = SANDBOX_PREFIX + f"{os.getpid()}.{secrets.token_hex(4)}"
    produced = observe(root, box)
    box_live = True
    try:
        if not produced:
            raise GateError("外掛在空沙盒零產出——外掛設定或 view 樹異常；「沒東西可驗」不算綠")
        odd = [rel for rel in produced if not RE_REL.match(rel) or ".." in rel.split("/")]
        if odd:
            raise GateError(f"外掛產出路徑不合 `src/…` 形：{odd}")
        problems, notes = [], []
        mismatch, missing, ghost = roster_verdict(produced, header_set, artifacts)
        if mismatch:
            problems.append("① 外掛實產出集 ≠ 工作樹帶產物檔頭之檔集\n"
                            f"    外掛實產出：{list(produced)}\n    帶檔頭者：{list(header_set)}\n"
                            "    → 產出檔未進工作樹、或手寫檔誤掛產物檔頭；兩集須一一對應")
        if missing:
            problems.append(f"① 憲法 §III.2 ★{TRACK} ({PURPOSE}) 列產物檔組漏列外掛實產出：{missing}\n"
                            f"    該組現列：{sorted(artifacts)}（該列全範圍欄：{sorted(declared)}）\n"
                            "    → 走憲法 §V.2 Amendment 補進該組（漏列＝該支無授權亦無守；列在該列其它群亦算漏列）")
        if ghost:
            problems.append(f"① 憲法 §III.2 ★{TRACK} ({PURPOSE}) 列產物檔組列著外掛不產出之路徑：{ghost}\n"
                            f"    外掛實產出：{list(produced)}\n"
                            "    → 走憲法 §V.2 Amendment 自該組移除（幽靈宣告＝授權射程虛胖、無任何機器守看管該支）")
        if len(artifacts) != claimed:
            problems.append(f"① 憲法該列注記自稱「產物檔 {claimed} 支」、注記所轄路徑實為 {len(artifacts)} 支：{sorted(artifacts)}\n"
                            "    → 支數字面與該組路徑同批改對（數量詞脫節＝下次讀憲法的人與本閘讀到不同名冊）")
        seeds = {}
        for name, seed_rel, _title, _fix in SEEDED:
            seed_root = os.path.join(root, seed_rel)
            if name == "baseline":
                if not os.path.isdir(seed_root):
                    notes.append(f"{TAG} ⤳ ③ 具名跳過：基線源倉 {BASELINE_REL}/ 缺席（跑 bash tools/bootstrap.sh 建置後自動恢復）"
                                 "——★此時 routes.ts 之手改無人看管")
                    continue
                lacking = [rel for rel in produced if not os.path.isfile(os.path.join(seed_root, *rel.split("/")))]
                if lacking:
                    raise GateError(f"基線源倉缺產物檔 {lacking}——上游結構變動？③之種子不完整即不能宣稱驗過")
            seeds[name] = {}
            for rel in produced:
                path = os.path.join(seed_root, *rel.split("/"))
                if os.path.isfile(path):
                    with open(path, "rb") as fh:
                        seeds[name][rel] = fh.read()
        box_live = False
        regen = regenerate(root, box, seeds)
    finally:
        if box_live:
            _sh(compose_argv("exec", "-T", SERVICE, "sh", "-c", CLEAN_SH, "sh", box), root)
    for name, _seed_rel, title, fix in SEEDED:
        if name in regen:
            problems += [f"{title}：{rel}\n    → {fix}\n{detail}" for rel, detail in compare_regenerated(regen[name], produced, worktree)]
    return problems, notes, len(produced)


def run_check(root, constitution_path):
    """→ (rc, 輸出行清單)。跳過邏輯住本檔內（ADR-00019）：跳過與通過在輸出上必須可辨。"""
    reason = docker_skip_reason(root)
    if reason:
        return 0, [f"{TAG} ⤳ 跳過：docker 不可用（{reason}）——docker 與 compose 檔就位後自動恢復實跑"]
    if not container_is_running(root):
        return 0, [f"{TAG} ⤳ 跳過：base-web 容器未在跑——起 stack 後自動恢復實跑：{START_HINT}"]
    t0 = time.perf_counter()
    try:
        problems, notes, count = _assertions(root, constitution_path)
    except GateError as ex:
        return 2, [f"{TAG} ✗ 環境或結構異常：{ex}"]
    if problems:
        return 1, notes + [f"{TAG} ✗ 路由外掛產物檔守門不通過："] + ["  " + p.replace("\n", "\n  ") for p in problems]
    ran = "②重算冪等" + ("" if notes else "與③零手改兩道")
    return 0, notes + [f"{TAG} ✓ 產出檔集 {count} 支＝產物檔頭集＝憲法列產物檔組（雙向）；{ran}皆 byte 相等（{time.perf_counter() - t0:.1f}s）"]


# ── self-test（離線；一律實跑上方生產函式、docker 以 subprocess 樁代）────────────────

ARTIFACTS = ("src/router/elegant/imports.ts", "src/router/elegant/routes.ts",
             "src/router/elegant/transform.ts", "src/typings/elegant-router.d.ts")
ROUTES = "src/router/elegant/routes.ts"
CANON = {rel: f"// {GENERATED_HEADER}\nexport const from = '{rel}';\nexport const keys = ['manage_ip-rule', 'manage_role'];\n".encode()
         for rel in ARTIFACTS}
CANON[ROUTES] = f"// {GENERATED_HEADER}\nroute manage_ip-rule = view.manage_ip-rule\nroute manage_role = view.manage_role\n".encode()
# 上游基線＝不含本頁之同四支（routes 少一條 route、其餘少一個鍵）
UPSTREAM = {rel: data.replace(b"route manage_ip-rule = view.manage_ip-rule\n", b"").replace(b"'manage_ip-rule', ", b"")
            for rel, data in CANON.items()}
SYN_ROW = ("| **★BASE-WEB-MANAGE-PAGE-WIRING** | (i) 管理頁進場 | `src/locales/langs/{en-us,zh-cn}.ts`（各 2 塊，新增型：`route:` 樹與 `page:` 樹）／"
           "`src/typings/app.d.ts`（1 塊）／`src/router/elegant/{imports,routes,transform}.ts`＋`src/typings/elegant-router.d.ts`（產物檔 4 支） | 紀律敘述 |\n")
SYN_CONSTITUTION = ("### III.1 預設\n\n| 軌道 | 範圍 | 紀律 |\n|---|---|---|\n"
                    "| **SYN-A** | `src/a/` | x |\n| **SYN-B** | `src/b/` | x |\n| **SYN-C** | `src/c/` | x |\n\n"
                    "### III.2 ★\n\n| 軌道 | 用途 | 範圍（檔案） | 紀律 |\n|---|---|---|---|\n"
                    "| **★SYN-OTHER** | (i) 別列 | `src/locales/langs/{en-us,zh-cn}.ts` | x |\n" + SYN_ROW + "\n## IV\n")
FAKE_DOCKER = "/usr/bin/docker"


def _write(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(data)


class _FakeRepo:
    """合成 repo 根：compose 兩檔＋憲法＋base-web 工作樹（產物四支＝CANON、另一支散文提及檔頭字樣之手寫檔）＋上游基線。"""

    def __init__(self, compose=True, baseline=True, constitution=SYN_CONSTITUTION):
        self._args = (compose, baseline, constitution)

    def __enter__(self):
        compose, baseline, constitution = self._args
        self._tmp = tempfile.TemporaryDirectory()
        root = self._tmp.name
        for name in COMPOSE_FILES if compose else ():
            _write(os.path.join(root, name), b"services: {}\n")
        _write(os.path.join(root, CONSTITUTION_REL), constitution.encode())
        for rel, data in CANON.items():
            _write(os.path.join(root, BASE_WEB_REL, rel), data)
            if baseline:
                _write(os.path.join(root, BASELINE_REL, rel), UPSTREAM[rel])
        _write(os.path.join(root, BASE_WEB_REL, "src", "store", "route.ts"),
               b"\n" * HEADER_WINDOW + f"// 提及 {GENERATED_HEADER} 之手寫檔\n".encode())
        return root

    def __exit__(self, *_exc):
        self._tmp.cleanup()


def _done(argv, rc=0, stdout=b"", stderr=b""):
    return subprocess.CompletedProcess(argv, rc, stdout, stderr)


def _stub_merge(seed, canon):
    """外掛對 routes.ts 之增量合併的最小模型：種子已有之 route 條目原樣保留、缺的自 canon 補上。"""
    kept = {ln.split(b"=")[0]: ln for ln in (seed or b"").splitlines() if ln.startswith(b"route ")}
    return b"".join(kept.get(ln.split(b"=")[0], ln) + b"\n" for ln in canon.splitlines())


def _stub_docker(running=True, produced=ARTIFACTS, observe_rc=0, regen_rc=0, log=None):
    """樁 subprocess.run。重算模型取外掛之要害：routes.ts 走增量合併（[`_stub_merge`]）；其餘三支整份重寫＝CANON。"""
    def run(argv, **kw):
        if log is not None:
            log.append((list(argv), kw.get("input")))
        if "ps" in argv:
            return _done(argv, 0, b"c0ffee\n" if running else b"")
        if OBSERVE_SH in argv:
            return _done(argv, observe_rc, b"[elegant-router] log\n__FILES__" + json.dumps(list(produced)).encode() + b"\n",
                         b"" if observe_rc == 0 else "外掛載入失敗".encode())
        if REGEN_SH in argv:
            if regen_rc:
                return _done(argv, regen_rc, b"", "沙盒 baseline 重算失敗：".encode())
            seeds, out = unpack_tar(kw["input"]), {}
            for box in argv[argv.index(REGEN_SH) + 3:]:
                for rel in produced:
                    out[f"{box}/{rel}"] = _stub_merge(seeds.get(f"{box}/{rel}"), CANON[rel]) if rel == ROUTES else CANON[rel]
            return _done(argv, 0, pack_tar(out))
        if CLEAN_SH in argv:
            return _done(argv)
        raise AssertionError(f"未預期之外部呼叫：{argv}")
    return run


def _check(root, constitution=None, **stub):
    with unittest.mock.patch("shutil.which", return_value=FAKE_DOCKER), \
            unittest.mock.patch("subprocess.run", side_effect=_stub_docker(**stub)):
        return run_check(root, constitution or os.path.join(root, CONSTITUTION_REL))


class TestRoster(unittest.TestCase):
    def test_declared_set_expands_braces_and_artifact_group_is_split_out(self):
        with _FakeRepo() as root:
            declared, artifacts, claimed = load_declared(os.path.join(root, CONSTITUTION_REL))
        self.assertEqual(declared, frozenset(ARTIFACTS) | {"src/locales/langs/en-us.ts", "src/locales/langs/zh-cn.ts", "src/typings/app.d.ts"})
        self.assertEqual((artifacts, claimed), (frozenset(ARTIFACTS), len(ARTIFACTS)))   # 同欄之 locale／app.d.ts 不入產物檔組

    def test_artifact_note_absent_fails_loud(self):
        with _FakeRepo(constitution=SYN_CONSTITUTION.replace("（產物檔 4 支）", "（產物檔紀律）")) as root:
            with self.assertRaises(GateError):
                load_declared(os.path.join(root, CONSTITUTION_REL))

    def test_missing_row_or_purpose_and_broken_structure_fail_loud(self):
        for broken in (SYN_CONSTITUTION.replace(TRACK, "SYN-RENAMED"),
                       SYN_CONSTITUTION.replace("| (i) 管理頁進場 |", "| (x) 別的用途 |"),
                       SYN_CONSTITUTION.replace("### III.2", "### III-2")):
            with _FakeRepo(constitution=broken) as root, contextlib.redirect_stderr(io.StringIO()):
                with self.assertRaises(GateError):
                    load_declared(os.path.join(root, CONSTITUTION_REL))

    def test_roster_verdict_pairs(self):
        group, ghost = frozenset(ARTIFACTS), "src/router/elegant/legacy.ts"
        self.assertEqual(roster_verdict(ARTIFACTS, ARTIFACTS, group), (False, [], []))
        self.assertEqual(roster_verdict(ARTIFACTS, ARTIFACTS, group - {ARTIFACTS[3]}), (False, [ARTIFACTS[3]], []))
        self.assertEqual(roster_verdict(ARTIFACTS, ARTIFACTS, group | {ghost}), (False, [], [ghost]))   # 雙向：幽靈宣告那一邊
        self.assertEqual(roster_verdict(ARTIFACTS, ARTIFACTS[:-1], group), (True, [], []))
        self.assertEqual(roster_verdict(ARTIFACTS[:-1], ARTIFACTS, group), (True, [], [ARTIFACTS[3]]))

    def test_header_scan_is_limited_to_head_window(self):
        with _FakeRepo() as root:
            self.assertEqual(scan_generated(os.path.join(root, BASE_WEB_REL)), tuple(sorted(ARTIFACTS)))


class TestCompare(unittest.TestCase):
    def test_equal_is_green_and_single_line_edit_is_red_with_diff(self):
        with _FakeRepo() as root:
            wt = os.path.join(root, BASE_WEB_REL)
            self.assertEqual(compare_regenerated(dict(CANON), ARTIFACTS, wt), [])
            _write(os.path.join(wt, ARTIFACTS[3]), CANON[ARTIFACTS[3]].replace(b"manage_ip-rule", b"manage_ipRule"))
            bad = compare_regenerated(dict(CANON), ARTIFACTS, wt)
        self.assertEqual([rel for rel, _ in bad], [ARTIFACTS[3]])
        self.assertIn("manage_ipRule", bad[0][1])

    def test_file_missing_on_either_side_is_red(self):
        with _FakeRepo() as root:
            wt = os.path.join(root, BASE_WEB_REL)
            regen = {rel: data for rel, data in CANON.items() if rel != ARTIFACTS[0]}
            self.assertEqual([rel for rel, _ in compare_regenerated(regen, ARTIFACTS, wt)], [ARTIFACTS[0]])
            os.remove(os.path.join(wt, ARTIFACTS[1]))
            self.assertEqual([rel for rel, _ in compare_regenerated(dict(CANON), ARTIFACTS, wt)], [ARTIFACTS[1]])


class TestRunCheck(unittest.TestCase):
    def test_skip_states_are_rc0_and_named(self):
        with _FakeRepo() as root, unittest.mock.patch("shutil.which", return_value=None), \
                unittest.mock.patch("subprocess.run", side_effect=AssertionError("不得呼叫")):
            rc, lines = run_check(root, os.path.join(root, CONSTITUTION_REL))
        self.assertEqual(rc, 0, lines)
        self.assertIn("跳過：docker 不可用", "\n".join(lines))
        with _FakeRepo(compose=False) as root, unittest.mock.patch("shutil.which", return_value=FAKE_DOCKER), \
                unittest.mock.patch("subprocess.run", side_effect=AssertionError("不得呼叫")):
            rc, lines = run_check(root, os.path.join(root, CONSTITUTION_REL))
        self.assertEqual(rc, 0, lines)
        self.assertIn(COMPOSE_FILES[0], "\n".join(lines))
        with _FakeRepo() as root:
            rc, lines = _check(root, running=False)
        self.assertEqual(rc, 0, lines)
        self.assertIn("base-web 容器未在跑", "\n".join(lines))

    def test_green_runs_all_three_assertions(self):
        with _FakeRepo() as root:
            rc, lines = _check(root)
        text = "\n".join(lines)
        self.assertEqual(rc, 0, text)
        self.assertIn("✓", text)
        self.assertNotIn("跳過", text)

    def test_hand_edit_of_merged_file_survives_worktree_seed_but_baseline_seed_catches_it(self):
        """③存在的理由：routes.ts 增量合併＝以工作樹為種時手改存活（②綠），只有基線為種那道紅。"""
        with _FakeRepo() as root:
            _write(os.path.join(root, BASE_WEB_REL, ROUTES), CANON[ROUTES].replace(b"view.manage_role", b"view.hacked"))
            rc, lines = _check(root)
        text = "\n".join(lines)
        self.assertEqual(rc, 1, text)
        self.assertIn("③", text)
        self.assertNotIn("②", text)
        self.assertIn("view.hacked", text)

    def test_stale_artifact_is_red_on_both_seeded_assertions(self):
        with _FakeRepo() as root:
            _write(os.path.join(root, BASE_WEB_REL, ARTIFACTS[3]), CANON[ARTIFACTS[3]].replace(b"'manage_ip-rule', ", b""))
            rc, lines = _check(root)
        text = "\n".join(lines)
        self.assertEqual(rc, 1, text)
        self.assertIn("②", text)
        self.assertIn("③", text)

    def test_constitution_artifact_group_is_compared_both_ways(self):
        """①之雙向：漏列（產出而未宣告）與幽靈宣告（宣告而不產出）各自即紅；注記支數與該組路徑同批對賬。"""
        odd = "src/router/elegant/legacy.ts"
        group = "＋`src/typings/elegant-router.d.ts`（產物檔 4 支）"
        cases = {   # 變體 → (期望命中字樣…)
            SYN_CONSTITUTION.replace(group, "（產物檔 3 支）"): ("漏列", ARTIFACTS[3]),
            SYN_CONSTITUTION.replace(group, f"＋`src/typings/elegant-router.d.ts`＋`{odd}`（產物檔 5 支）"): ("列著外掛不產出之路徑", odd),
            SYN_CONSTITUTION.replace(group, f"＋`src/typings/elegant-router.d.ts`＋`{odd}`（產物檔 4 支）"): ("自稱「產物檔 4 支」", odd),
            # 列在該列其它群（app.d.ts 那群）＝仍算漏列：①的另一邊是產物檔組、不是整欄
            SYN_CONSTITUTION.replace(group, "（產物檔 3 支）").replace("`src/typings/app.d.ts`（1 塊",
                                                                  "`src/typings/app.d.ts`＋`src/typings/elegant-router.d.ts`（1 塊"):
                ("漏列", ARTIFACTS[3]),
        }
        for constitution, wants in cases.items():
            with _FakeRepo(constitution=constitution) as root:
                rc, lines = _check(root)
            text = "\n".join(lines)
            self.assertEqual(rc, 1, text)
            for want in wants:
                self.assertIn(want, text)

    def test_produced_set_differs_from_header_set_is_red(self):
        with _FakeRepo() as root:
            rc, lines = _check(root, produced=ARTIFACTS[:-1])
        self.assertEqual(rc, 1, lines)
        self.assertIn("① 外掛實產出集 ≠", "\n".join(lines))

    def test_baseline_absent_skips_only_third_assertion_loudly(self):
        with _FakeRepo(baseline=False) as root:
            rc, lines = _check(root)
        text = "\n".join(lines)
        self.assertEqual(rc, 0, text)
        self.assertIn("③ 具名跳過", text)
        with _FakeRepo(baseline=False) as root:
            _write(os.path.join(root, BASE_WEB_REL, ARTIFACTS[0]), CANON[ARTIFACTS[0]] + b"// hand\n")
            rc, lines = _check(root)
        self.assertEqual(rc, 1, lines)
        self.assertIn("②", "\n".join(lines))

    def test_environment_and_structure_failures_are_rc2(self):
        cases = {
            "觀測失敗": dict(observe_rc=3),
            "零產出": dict(produced=()),
            "重算失敗": dict(regen_rc=3),
            "產出路徑不合形": dict(produced=("src/../etc/passwd",)),
        }
        for name, stub in cases.items():
            with _FakeRepo() as root:
                rc, lines = _check(root, **stub)
            self.assertEqual(rc, 2, (name, lines))
        with _FakeRepo() as root:
            os.remove(os.path.join(root, BASELINE_REL, ARTIFACTS[1]))
            rc, lines = _check(root)
        self.assertEqual(rc, 2, lines)
        self.assertIn("基線源倉缺", "\n".join(lines))
        with _FakeRepo() as root, contextlib.redirect_stderr(io.StringIO()):
            rc, lines = _check(root, constitution=os.path.join(root, "nope.md"))
        self.assertEqual(rc, 2, lines)

    def test_seeds_go_to_their_own_sandbox_and_no_path_leaves_a_sandbox_behind(self):
        log = []
        with _FakeRepo() as root:
            _check(root, log=log)
            regen = next(inp for argv, inp in log if REGEN_SH in argv)
            seeds = unpack_tar(regen)
            self.assertEqual({k: v for k, v in seeds.items() if k.startswith("worktree/")}, {"worktree/" + r: d for r, d in CANON.items()})
            self.assertEqual({k: v for k, v in seeds.items() if k.startswith("baseline/")}, {"baseline/" + r: d for r, d in UPSTREAM.items()})
            boxes = {argv[argv.index(s) + 2] for argv, _ in log for s in (OBSERVE_SH, REGEN_SH) if s in argv}
            self.assertEqual(len(boxes), 1)
            self.assertTrue(boxes.pop().startswith(SANDBOX_PREFIX))
            self.assertFalse(any(CLEAN_SH in argv for argv, _ in log), "重算段收場自清、綠路徑不另下清理")
        log = []
        with _FakeRepo() as root:
            os.remove(os.path.join(root, BASELINE_REL, ARTIFACTS[1]))
            _check(root, log=log)
        observed = [argv[argv.index(OBSERVE_SH) + 2] for argv, _ in log if OBSERVE_SH in argv]
        cleaned = [argv[argv.index(CLEAN_SH) + 2] for argv, _ in log if CLEAN_SH in argv]
        self.assertEqual((len(observed), cleaned), (1, observed), "觀測成功而未走到重算段＝須就地清沙盒")
        log = []
        with _FakeRepo(constitution=SYN_CONSTITUTION.replace(TRACK, "SYN-RENAMED")) as root, contextlib.redirect_stderr(io.StringIO()):
            _check(root, log=log)
        self.assertFalse(any(OBSERVE_SH in argv for argv, _ in log), "憲法列缺席應先於任何沙盒動作")


class TestDiscipline(unittest.TestCase):
    def test_container_side_only_reads_app(self):
        """唯讀不變式之字面釘：兩段 sh 對 `/app` 只有 symlink 來源一處、runner 只有載入外掛設定一處。"""
        for script in (OBSERVE_SH, REGEN_SH):
            self.assertEqual(re.findall(r"/app\S*", script), ["/app/src/views"])
        self.assertEqual(re.findall(r"/app[^'\"\s]*", NODE_RUNNER), ["/app/build/plugins/router.ts"])

    def test_usage_guard(self):
        for argv in (["p", "nope"], ["p", "check", "--constitution"], ["p", "check", "extra"]):
            err = io.StringIO()
            with contextlib.redirect_stderr(err):
                self.assertEqual(main(argv), 64, argv)
            self.assertIn("用法：", err.getvalue())


def main(argv):
    args = list(argv[1:])
    constitution = os.path.join(REPO_ROOT, CONSTITUTION_REL)
    if "--constitution" in args:
        idx = args.index("--constitution")
        if idx + 1 >= len(args):
            _say(USAGE, err=True)
            return 64
        constitution = args[idx + 1]
        del args[idx:idx + 2]
    cmd = args[0] if args else "check"
    if cmd == "test" and len(args) == 1:
        ok = unittest.main(argv=[argv[0]], exit=False, verbosity=1).result.wasSuccessful()
        if ok:
            _say(f"{TAG} ✓ self-test 過（憲法列同源解析與 fail-loud／產物檔組切出／①判定核成對／②③比對核成對／三跳過態／"
                 f"手改存活於工作樹種而紅於基線種／憲法漏列與幽靈宣告雙向紅＋注記支數對賬／rc 2 諸態／種子歸位／容器側唯讀字面／用法守衛）")
        return 0 if ok else 1
    if cmd != "check" or len(args) > 1:
        _say(USAGE, err=True)
        return 64
    rc, lines = run_check(REPO_ROOT, constitution)
    for ln in lines:
        _say(ln, err=bool(rc))
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
